## Load the required packages

In [1]:
import anndata
import pandas as pd
import numpy as np
import scanpy as sc
import torch
import torch.nn.functional as F
from pathlib import Path
import os

## Set path

In [2]:
working_dir = Path(os.getcwd())
base_dir = f"{working_dir.parents[0]}/outputs/batch variation/208_M2-208_M1"

## Load base results

In [3]:
base_methods = ["Babel", "cTPnet", "Dengkw", "Liger", "moETM", "sciPENN", "scMM", "scMOG", "scMoGNN", "scVAEIT", "Seurat", "TotalVI"]
base_results = {}
for name in base_methods:
    if name == "scMOG":
        results = anndata.read(f"{base_dir}/{name}/RNA_protein_adata.h5ad")
        results = pd.DataFrame(results.X.toarray(), index=results.obs.index, columns=results.var.index)
        base_results[name] = results
    
    elif name == "Liger":
        results = pd.read_csv(f"{base_dir}/{name}/test_predicted_protein_expression ({name}).csv", index_col=0).T
        base_results[name] = results
        
    elif name == "Seurat":
        results = pd.read_table(f"{base_dir}/{name}/test_predicted_protein_expression ({name}).txt", index_col=0, sep=" ").T
        base_results[name] = results
        
    else:
        results = pd.read_csv(f"{base_dir}/{name}/test_predicted_protein_expression ({name}).csv", index_col=0)
        base_results[name] = results

## Recover the protein names in cTPnet, Liger, and Seurat

In [4]:
cTPnet_protein_names_convert = pd.read_csv(f"{base_dir}/cTPnet/cTPnet_protein_names_convert.csv", index_col=0)
cTPnet_protein_names_convert.set_index("convert_name", inplace=True)
Liger_protein_names_convert = pd.read_csv(f"{base_dir}/Liger/Liger_protein_names_convert.csv", index_col=0)
Liger_protein_names_convert.set_index("convert_name", inplace=True)
Seurat_protein_names_convert = pd.read_csv(f"{base_dir}/Seurat/Seurat_protein_names_convert.csv", index_col=0)
Seurat_protein_names_convert.set_index("convert_name", inplace=True)

base_results["cTPnet"].columns = cTPnet_protein_names_convert.loc[base_results["cTPnet"].columns, "original_name"].values
base_results["Liger"].columns = Liger_protein_names_convert.loc[base_results["Liger"].columns, "original_name"].values
base_results["Seurat"].columns = Seurat_protein_names_convert.loc[base_results["Seurat"].columns, "original_name"].values

## Align rows and columns of all base results to the first one as reference

In [5]:
base_df = base_results[base_methods[0]]
base_index = base_df.index
base_columns = base_df.columns
for key, df in base_results.items():
    base_results[key] = df.reindex(index=base_index, columns=base_columns)

## Verify that rows and columns have the same order across base results

In [6]:
for key, df in base_results.items():
    same_index = (df.index.equals(base_index))
    same_columns = (df.columns.equals(base_columns))
    print(f"{key}: index aligned? {same_index}, columns aligned? {same_columns}")

Babel: index aligned? True, columns aligned? True
cTPnet: index aligned? True, columns aligned? True
Dengkw: index aligned? True, columns aligned? True
Liger: index aligned? True, columns aligned? True
moETM: index aligned? True, columns aligned? True
sciPENN: index aligned? True, columns aligned? True
scMM: index aligned? True, columns aligned? True
scMOG: index aligned? True, columns aligned? True
scMoGNN: index aligned? True, columns aligned? True
scVAEIT: index aligned? True, columns aligned? True
Seurat: index aligned? True, columns aligned? True
TotalVI: index aligned? True, columns aligned? True

## Convert log-scale base results back to the original scale by exponentiation

In [7]:
need_exp = ["Babel", "cTPnet", "Dengkw", "sciPENN", "scMOG", "scMoGNN", "scVAEIT", "Seurat"]
for key, df in base_results.items():
    if key in need_exp:
        base_results[key] = np.exp(df)
    
    else:
        base_results[key] = df.copy()

## Normalize base results

In [8]:
def log_normalize(data, target_sum=10000):
    adata = anndata.AnnData(X=data)
    sc.pp.normalize_total(adata, target_sum=target_sum)
    sc.pp.log1p(adata)
    return pd.DataFrame(adata.X, index=adata.obs.index, columns=adata.var.index)

def Z_score(data):
    adata = anndata.AnnData(X=data)
    sc.pp.scale(adata)
    return pd.DataFrame(adata.X, index=adata.obs.index, columns=adata.var.index)

base_results_ln = {k: log_normalize(v.copy()) for k, v in base_results.items()}
base_results_zs = {k: log_normalize(v.copy()) for k, v in base_results_ln.items()}

## Define a function to compute cosine distance

In [9]:
def cosine_distance_sum(H1: torch.Tensor, H2: torch.Tensor) -> torch.Tensor:
    assert H1.shape == H2.shape, "H1 and H2 must have the same shape"
    N, P = H1.shape
#
    row_norm_H1 = H1.norm(dim=1)
    row_norm_H2 = H2.norm(dim=1)
    row_valid = (row_norm_H1 > 0) & (row_norm_H2 > 0)
#
    A = F.normalize(H1[row_valid], dim=1)
    B = F.normalize(H2[row_valid], dim=1)
    row_cos_sim = (A * B).sum(dim=1)
    row_dist = torch.full((N,), 2.0, device=H1.device)
    row_dist[row_valid] = 1 - row_cos_sim
    row_loss = row_dist.mean()
#
    H1_T = H1.T
    H2_T = H2.T
    col_norm_H1 = H1_T.norm(dim=1)
    col_norm_H2 = H2_T.norm(dim=1)
    col_valid = (col_norm_H1 > 0) & (col_norm_H2 > 0)
#
    A_T = F.normalize(H1_T[col_valid], dim=1)
    B_T = F.normalize(H2_T[col_valid], dim=1)
    col_cos_sim = (A_T * B_T).sum(dim=1)
    col_dist = torch.full((P,), 2.0, device=H1.device)
    col_dist[col_valid] = 1 - col_cos_sim
    col_loss = col_dist.mean()
#
    return row_loss + col_loss

## Calculate the naive average of the base results

In [10]:
base_results_zs = list(base_results_zs.values())
M = len(base_results_zs)
mean_res = sum(base_results_zs) / len(base_results_zs)
mean_res

,ADT_4-1BBLigand(CD137L)_A0890,ADT_CD102_A0104,ADT_CD103_A0201,ADT_CD105_A0812,ADT_CD106_A0226,ADT_CD107a(LAMP-1)_A0905,ADT_CD115(CSF-1R)_A0105,ADT_CD117(c-Kit)_A0012,ADT_CD11a_A0595,ADT_CD11b_A0014,...,ADT_TCRVr3_A0210,ADT_TCRbchain_A0120,ADT_TCRr-d_A0121,ADT_TER-119-ErythroidCells_A0122,ADT_TIGIT(Vstm3)_A0848,ADT_TLR4(CD284)-MD2Complex_A0875,ADT_Tim-4_A0567,ADT_XCR1_A0568,ADT_anti-P2RY12_A0415,ADT_integrinb7_A0214
index,,,,,,,,,,,,,,,,,,,,,
AAACCCAAGCGATCGA-1,3.762014,4.179905,4.235006,3.833395,3.847665,3.463089,3.758950,3.974681,4.451051,3.463900,...,4.026074,4.254517,3.862129,3.521792,4.066590,3.774194,3.920286,3.837776,3.910805,4.410877
AAACCCACACCTCTAC-1,3.793056,4.302042,3.946241,3.790181,3.909536,3.802155,3.806943,3.831318,4.361076,3.853334,...,3.978614,3.804478,3.827622,3.252525,4.041994,3.778148,4.012038,3.798774,3.890942,4.131676
AAACCCACACGTCGTG-1,3.789724,4.394031,3.966532,3.498961,3.885261,3.748854,3.785270,3.822779,4.262487,3.865209,...,4.014831,3.503383,3.861780,3.241684,4.022119,3.819564,3.958819,3.787467,3.902275,4.164600
AAACCCACATGTCTAG-1,3.799661,4.363760,3.957075,3.786614,3.888182,3.807688,3.785386,3.760519,4.290310,3.847821,...,4.005929,3.779281,3.858604,3.513225,4.054255,3.750814,3.993867,3.781849,3.916672,4.164496
AAACCCAGTCAAAGTA-1,3.456553,4.305390,3.942046,3.760663,3.876785,3.769105,3.817566,3.882949,4.337999,3.508797,...,4.010127,3.869772,3.525175,3.207823,4.052586,3.773986,3.966206,3.836206,3.919435,4.239667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TTTGTTGCATTCCTCG-1,3.779138,4.319893,3.926904,3.827325,3.870665,3.470368,3.783847,3.847224,4.318328,3.936066,...,3.996255,3.812528,3.862926,3.217557,4.034974,3.800616,3.969103,3.484411,3.916634,4.237754
TTTGTTGGTGCTCTTC-1,3.765122,4.310352,3.946872,3.777145,3.883072,3.815306,3.798374,3.784503,4.288279,3.868408,...,3.991827,3.826446,3.834443,3.454972,4.048337,3.804723,3.972051,3.807993,3.892137,4.210668
TTTGTTGTCAGCCTTC-1,3.816451,4.181170,3.944892,3.784502,3.874308,3.779820,3.808163,3.937730,4.447227,3.856363,...,4.035530,4.380803,3.522913,3.503627,4.076241,3.833734,3.984084,3.846434,3.902951,4.125801
TTTGTTGTCCCTTGGT-1,3.795483,4.186496,4.195987,3.872051,3.851604,3.798902,3.790674,3.943395,4.457910,3.827340,...,4.013281,4.255092,3.877669,3.239730,4.068732,3.841439,3.971112,3.809890,3.924223,4.384999
TTTGTTGTCTTACTGT-1,3.501530,4.307764,3.975968,3.843692,3.873889,3.761988,3.837467,3.826942,4.228564,3.820537,...,4.018778,3.876329,3.879639,3.574494,4.074566,3.844858,3.928624,3.848648,3.886081,4.165395

In [11]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
H0 = torch.tensor(mean_res.values, dtype=torch.float32, device=device)
H_list = [torch.tensor(h.values, dtype=torch.float32, device=device) for h in base_results_zs]
alpha = torch.zeros(M, requires_grad=True, device=device)
optimizer = torch.optim.Adam([alpha], lr=0.1)

## Empirically set the values of lambda

In [12]:
cos_dist_init = [cosine_distance_sum(H0, Hm).item() for Hm in H_list]
lamda = np.median(cos_dist_init)
cos_dist_init, lamda

([0.0010900360066443682,
  0.000797063228674233,
  0.0010905256494879723,
  0.0015214059967547655,
  0.0018858581315726042,
  0.0025300614070147276,
  0.08953037112951279,
  0.0008601216832175851,
  0.0011674228589981794,
  0.003467781934887171,
  0.0011312206042930484,
  0.0008821339579299092],
 0.001149321731645614)

## Start optimization

In [13]:
loss_list = []
cos_dist_list = []
for step in range(500):
    optimizer.zero_grad()
#
    weights = F.softmax(alpha, dim=0)  # (M,)
#
    H_ens = sum(w * H for w, H in zip(weights, H_list))  # (N, D)
#
    cos_dist = 0.0
    for w, Hm in zip(weights, H_list):
        dist = cosine_distance_sum(H_ens, Hm)
        cos_dist += w * dist
#   
    loss = cos_dist + lamda * (weights * torch.log(weights + 1e-8)).sum()
#
    loss.backward()
    optimizer.step()
    loss_list.append(loss.item())
    cos_dist_list.append(cos_dist.item())
#
    print(f"Step {step}: Loss = {loss.item():.4f}, Weights = {weights.detach().cpu().numpy()}")

Step 0: Loss = 0.0060, Weights = [0.08333334 0.08333334 0.08333334 0.08333334 0.08333334 0.08333334
 0.08333334 0.08333334 0.08333334 0.08333334 0.08333334 0.08333334]
Step 1: Loss = 0.0047, Weights = [0.08461145 0.08461145 0.08461145 0.08461144 0.08461143 0.08461141
 0.06927411 0.08461145 0.08461145 0.08461139 0.08461145 0.08461145]
Step 2: Loss = 0.0037, Weights = [0.08569039 0.08568902 0.08569048 0.08567866 0.0856713  0.08567554
 0.0575055  0.08568843 0.08569004 0.08564484 0.08569023 0.08568561]
Step 3: Loss = 0.0028, Weights = [0.08660594 0.08660088 0.08660625 0.08655986 0.08653041 0.08654623
 0.04773413 0.08659858 0.08660452 0.08642032 0.08660528 0.08658762]
Step 4: Loss = 0.0020, Weights = [0.08739516 0.08738321 0.08739591 0.08727948 0.08720413 0.08724205
 0.03967507 0.08737739 0.0873915  0.08691242 0.08739343 0.08735023]
Step 5: Loss = 0.0014, Weights = [0.08809482 0.08807193 0.08809633 0.08786052 0.08770534 0.08777903
 0.03306198 0.08806009 0.08808724 0.08708584 0.08809123 0.08800565]
Step 6: Loss = 0.0009, Weights = [0.08873983 0.08870115 0.08874248 0.08832376 0.08804428 0.08817046
 0.02765401 0.08868007 0.08872615 0.08690025 0.08873332 0.08858425]
Step 7: Loss = 0.0004, Weights = [0.08936179 0.08930173 0.08936603 0.08868705 0.08822863 0.08842684
 0.02323953 0.08926747 0.08933926 0.08631743 0.08935104 0.08911321]
Step 8: Loss = 0.0001, Weights = [0.0899878  0.08990008 0.08999415 0.08896457 0.08826361 0.08855577
 0.01963704 0.08984801 0.08995321 0.08530904 0.08997125 0.08961543]
Step 9: Loss = -0.0002, Weights = [0.0906397  0.09051738 0.09064872 0.08916654 0.08815217 0.08856214
 0.01669395 0.09044228 0.09058929 0.08386342 0.09061552 0.09010889]
Step 10: Loss = -0.0005, Weights = [0.09133368 0.09116922 0.09134602 0.08929903 0.08789545 0.08844843
 0.01428404 0.09106529 0.09126329 0.08198954 0.09129985 0.09060615]
Step 11: Loss = -0.0007, Weights = [0.09208062 0.09186586 0.0920969  0.08936439 0.08749333 0.08821522
 0.01230417 0.09172677 0.09198563 0.07971755 0.09203484 0.09111472]
Step 12: Loss = -0.0008, Weights = [0.09288651 0.09261273 0.09290744 0.08936186 0.08694525 0.08786203
 0.01067093 0.09243171 0.09276187 0.07709588 0.09282631 0.09163755]
Step 13: Loss = -0.0010, Weights = [0.0937534  0.09341127 0.09377968 0.08928838 0.08625101 0.08738808
 0.00931729 0.09318114 0.09359368 0.07418617 0.0936761  0.09217384]
Step 14: Loss = -0.0011, Weights = [0.09468032 0.09425991 0.09471264 0.08913965 0.08541161 0.08679323
 0.00818962 0.09397312 0.09447971 0.07105727 0.09458298 0.09271999]
Step 15: Loss = -0.0012, Weights = [0.09566406 0.09515487 0.09570315 0.08891092 0.08442979 0.08607849
 0.00724514 0.09480359 0.09541641 0.06777946 0.09554361 0.0932705 ]
Step 16: Loss = -0.0013, Weights = [0.09670002 0.09609096 0.09674659 0.0885978  0.08331054 0.08524666
 0.00644971 0.0956671  0.09639886 0.06441985 0.09655318 0.09381868]
Step 17: Loss = -0.0014, Weights = [0.09778278 0.09706217 0.09783752 0.08819676 0.0820611  0.08430243
 0.00577609 0.09655741 0.09742133 0.06103903 0.0976061  0.09435735]
Step 18: Loss = -0.0014, Weights = [0.09890646 0.09806197 0.09897005 0.08770552 0.08069087 0.08325244
 0.00520247 0.09746788 0.09847768 0.05768912 0.09869633 0.09487911]
Step 19: Loss = -0.0015, Weights = [0.10006516 0.09908389 0.10013825 0.08712328 0.07921127 0.08210518
 0.00471137 0.09839199 0.09956179 0.05441299 0.09981782 0.09537698]
Step 20: Loss = -0.0015, Weights = [0.101253   0.10012143 0.10133625 0.08645075 0.07763523 0.08087061
 0.00428869 0.09932321 0.10066763 0.05124425 0.10096459 0.09584429]
Step 21: Loss = -0.0016, Weights = [0.1024644  0.10116842 0.10255838 0.0856902  0.0759768  0.0795599
 0.00392305 0.1002554  0.10178944 0.04820794 0.10213096 0.09627508]
Step 22: Loss = -0.0016, Weights = [0.10369404 0.10221895 0.10379932 0.08484527 0.07425071 0.07818501
 0.00360518 0.10118283 0.10292187 0.04532138 0.10331151 0.09666399]
Step 23: Loss = -0.0017, Weights = [0.10493691 0.10326743 0.10505401 0.08392089 0.07247183 0.07675835
 0.00332752 0.1021001  0.10405984 0.04259534 0.1045012  0.09700649]
Step 24: Loss = -0.0017, Weights = [0.10618846 0.10430873 0.10631783 0.08292306 0.07065496 0.07529241
 0.0030839  0.10300236 0.10519885 0.04003521 0.10569543 0.09729885]
Step 25: Loss = -0.0017, Weights = [0.10744435 0.10533803 0.10758641 0.08185861 0.06881423 0.07379944
 0.00286919 0.10388515 0.10633468 0.03764197 0.10688993 0.09753802]
Step 26: Loss = -0.0018, Weights = [0.10870072 0.10635093 0.10885581 0.08073509 0.06696305 0.07229123
 0.00267918 0.10474449 0.10746359 0.03541332 0.10808084 0.0977218 ]
Step 27: Loss = -0.0018, Weights = [0.10995395 0.10734338 0.11012238 0.07956044 0.06511378 0.07077882
 0.00251035 0.10557686 0.10858227 0.03334439 0.10926466 0.09784872]
Step 28: Loss = -0.0018, Weights = [0.11120083 0.10831178 0.11138285 0.07834288 0.0632776  0.06927249
 0.00235977 0.1063792  0.10968774 0.0314286  0.11043826 0.09791805]
Step 29: Loss = -0.0018, Weights = [0.11243843 0.10925281 0.11263418 0.07709069 0.06146444 0.06778147
 0.00222497 0.10714887 0.11077744 0.02965811 0.11159886 0.09792973]
Step 30: Loss = -0.0018, Weights = [0.11366411 0.11016361 0.11387371 0.07581203 0.05968295 0.06631403
 0.00210388 0.10788366 0.11184918 0.02802444 0.11274403 0.09788434]
Step 31: Loss = -0.0019, Weights = [0.11487556 0.11104157 0.11509902 0.07451488 0.05794049 0.06487739
 0.00199474 0.10858177 0.11290114 0.02651871 0.11387166 0.09778309]
Step 32: Loss = -0.0019, Weights = [0.11607066 0.11188452 0.11630796 0.07320679 0.05624317 0.06347772
 0.00189605 0.10924179 0.11393175 0.02513202 0.11497992 0.09762762]
Step 33: Loss = -0.0019, Weights = [0.11724763 0.11269059 0.11749862 0.07189491 0.05459595 0.06212024
 0.00180654 0.10986267 0.11493981 0.02385557 0.11606728 0.09742018]
Step 34: Loss = -0.0019, Weights = [0.11840483 0.11345822 0.11866933 0.07058587 0.05300266 0.06080916
 0.00172511 0.11044373 0.11592437 0.0226809  0.11713243 0.0971633 ]
Step 35: Loss = -0.0019, Weights = [0.11954094 0.11418616 0.11981864 0.06928571 0.05146618 0.0595479
 0.00165084 0.11098461 0.11688472 0.02159992 0.11817433 0.09685996]
Step 36: Loss = -0.0019, Weights = [0.12065472 0.11487348 0.12094527 0.06799991 0.04998847 0.058339
 0.00158291 0.11148524 0.11782046 0.02060499 0.11919218 0.09651335]
Step 37: Loss = -0.0019, Weights = [0.12174516 0.11551952 0.12204812 0.06673329 0.04857072 0.05718433
 0.00152061 0.11194585 0.11873126 0.01968897 0.12018531 0.09612691]
Step 38: Loss = -0.0019, Weights = [0.12281136 0.11612381 0.12312623 0.06549008 0.04721342 0.05608511
 0.00146334 0.11236685 0.11961708 0.01884521 0.12115328 0.09570418]
Step 39: Loss = -0.0019, Weights = [0.12385266 0.11668625 0.12417885 0.06427394 0.04591649 0.05504198
 0.00141057 0.11274902 0.12047801 0.01806756 0.12209582 0.09524887]
Step 40: Loss = -0.0020, Weights = [0.12486841 0.11720689 0.12520528 0.06308793 0.04467936 0.05405511
 0.00136182 0.11309317 0.12131426 0.01735037 0.12301268 0.09476469]
Step 41: Loss = -0.0020, Weights = [0.12585814 0.11768602 0.12620495 0.06193458 0.04350106 0.05312429
 0.00131671 0.11340044 0.12212612 0.01668845 0.12390383 0.09425535]
Step 42: Loss = -0.0020, Weights = [0.12682146 0.11812413 0.12717742 0.06081593 0.04238029 0.05224892
 0.00127485 0.113672   0.12291407 0.01607703 0.12476936 0.09372452]
Step 43: Loss = -0.0020, Weights = [0.12775804 0.11852185 0.1281223  0.05973355 0.04131547 0.05142815
 0.00123595 0.11390919 0.12367855 0.01551178 0.12560937 0.09317581]
Step 44: Loss = -0.0020, Weights = [0.12866764 0.11888    0.12903935 0.05868857 0.04030483 0.05066088
 0.00119972 0.11411349 0.12442008 0.01498872 0.12642401 0.09261267]
Step 45: Loss = -0.0020, Weights = [0.12955011 0.11919963 0.12992829 0.0576818  0.03934647 0.04994585
 0.0011659  0.11428642 0.12513933 0.01450427 0.12721361 0.09203839]
Step 46: Loss = -0.0020, Weights = [0.13040529 0.11948178 0.130789   0.05671364 0.03843836 0.04928163
 0.00113429 0.11442959 0.1258368  0.01405511 0.12797838 0.09145616]
Step 47: Loss = -0.0020, Weights = [0.13123317 0.11972768 0.13162138 0.05578426 0.03757843 0.04866673
 0.00110468 0.11454462 0.12651314 0.01363827 0.1287187  0.09086891]
Step 48: Loss = -0.0020, Weights = [0.13203372 0.1199387  0.13242537 0.05489353 0.03676456 0.04809956
 0.0010769  0.11463324 0.127169   0.01325104 0.12943493 0.09027945]
Step 49: Loss = -0.0020, Weights = [0.13280696 0.12011627 0.13320099 0.05404112 0.03599464 0.04757848
 0.00105079 0.11469713 0.12780495 0.01289093 0.1301274  0.08969034]
Step 50: Loss = -0.0020, Weights = [0.13355294 0.12026189 0.13394828 0.05322653 0.03526656 0.04710184
 0.0010262  0.114738   0.1284216  0.01255571 0.13079654 0.08910394]
Step 51: Loss = -0.0020, Weights = [0.13427176 0.12037707 0.13466734 0.05244906 0.03457825 0.04666797
 0.00100302 0.11475754 0.1290195  0.01224333 0.13144271 0.08852241]
Step 52: Loss = -0.0020, Weights = [0.13496357 0.12046348 0.13535835 0.05170792 0.03392769 0.04627524
 0.00098113 0.11475743 0.1295992  0.01195193 0.13206634 0.0879477 ]
Step 53: Loss = -0.0020, Weights = [0.13562854 0.12052275 0.13602145 0.0510022  0.03331292 0.045922
 0.00096041 0.11473931 0.1301612  0.01167981 0.13266782 0.08738156]
Step 54: Loss = -0.0020, Weights = [0.13626689 0.12055656 0.13665687 0.05033094 0.03273205 0.04560665
 0.00094079 0.11470479 0.13070597 0.01142545 0.13324754 0.08682554]
Step 55: Loss = -0.0020, Weights = [0.13687885 0.12056659 0.13726486 0.04969304 0.03218322 0.04532761
 0.00092218 0.11465539 0.13123396 0.01118742 0.13380589 0.08628096]
Step 56: Loss = -0.0020, Weights = [0.13746466 0.12055454 0.13784575 0.04908745 0.0316647  0.04508337
 0.00090449 0.11459269 0.1317456  0.01096446 0.13434325 0.08574908]
Step 57: Loss = -0.0020, Weights = [0.13802463 0.12052206 0.1383999  0.04851301 0.0311748  0.04487243
 0.00088767 0.11451807 0.1322412  0.0107554  0.13486    0.08523085]
Step 58: Loss = -0.0020, Weights = [0.13855915 0.12047088 0.13892764 0.04796859 0.03071193 0.04469336
 0.00087164 0.11443291 0.13272113 0.01055917 0.13535652 0.08472712]
Step 59: Loss = -0.0020, Weights = [0.13906851 0.12040259 0.13942942 0.04745304 0.03027456 0.04454474
 0.00085634 0.11433858 0.13318563 0.01037479 0.13583319 0.08423858]
Step 60: Loss = -0.0020, Weights = [0.13955317 0.12031883 0.13990568 0.0469652  0.02986125 0.04442525
 0.00084174 0.11423629 0.133635   0.01020138 0.13629042 0.08376581]
Step 61: Loss = -0.0020, Weights = [0.14001356 0.12022116 0.14035694 0.04650393 0.02947062 0.04433356
 0.00082777 0.11412724 0.13406947 0.01003812 0.13672848 0.08330923]
Step 62: Loss = -0.0020, Weights = [0.1404501  0.12011106 0.14078373 0.04606809 0.02910138 0.04426842
 0.00081439 0.1140125  0.1344892  0.00988426 0.1371478  0.08286915]
Step 63: Loss = -0.0020, Weights = [0.14086334 0.11999004 0.14118657 0.04565658 0.02875229 0.04422862
 0.00080156 0.11389311 0.1348944  0.00973911 0.13754869 0.08244575]
Step 64: Loss = -0.0020, Weights = [0.14125374 0.11985946 0.14156608 0.04526831 0.0284222  0.04421297
 0.00078925 0.11377005 0.1352852  0.00960206 0.13793151 0.08203913]
Step 65: Loss = -0.0020, Weights = [0.14162195 0.11972072 0.1419229  0.04490222 0.02811002 0.04422032
 0.00077742 0.1136442  0.13566177 0.00947252 0.13829666 0.08164933]
Step 66: Loss = -0.0020, Weights = [0.14196847 0.11957506 0.14225769 0.04455727 0.0278147  0.0442496
 0.00076604 0.11351635 0.13602418 0.00934996 0.13864446 0.08127625]
Step 67: Loss = -0.0020, Weights = [0.14229396 0.11942369 0.14257109 0.04423247 0.02753528 0.0442997
 0.00075508 0.11338727 0.13637254 0.0092339  0.13897528 0.08091976]
Step 68: Loss = -0.0020, Weights = [0.14259905 0.11926777 0.14286382 0.04392684 0.02727083 0.04436959
 0.00074451 0.11325764 0.13670698 0.00912388 0.13928945 0.08057968]
Step 69: Loss = -0.0020, Weights = [0.14288434 0.11910836 0.1431366  0.04363947 0.0270205  0.04445825
 0.00073432 0.11312807 0.13702755 0.00901949 0.13958737 0.08025572]
Step 70: Loss = -0.0020, Weights = [0.14315057 0.11894642 0.14339018 0.04336943 0.02678348 0.0445647
 0.00072447 0.1129991  0.13733438 0.00892036 0.13986939 0.07994754]
Step 71: Loss = -0.0020, Weights = [0.1433984  0.11878291 0.14362532 0.04311587 0.02655898 0.04468797
 0.00071494 0.11287124 0.13762751 0.00882612 0.14013594 0.07965486]
Step 72: Loss = -0.0020, Weights = [0.14362854 0.11861868 0.14384276 0.04287794 0.02634631 0.0448271
 0.00070572 0.11274487 0.13790706 0.00873646 0.14038734 0.07937723]
Step 73: Loss = -0.0020, Weights = [0.1438417  0.11845449 0.14404325 0.04265485 0.02614477 0.04498117
 0.00069679 0.11262041 0.1381732  0.00865107 0.14062402 0.07911425]
Step 74: Loss = -0.0020, Weights = [0.14403863 0.11829107 0.14422764 0.04244583 0.02595374 0.04514928
 0.00068813 0.11249819 0.13842598 0.00856968 0.1408464  0.07886548]
Step 75: Loss = -0.0020, Weights = [0.14422007 0.11812904 0.14439663 0.04225013 0.02577261 0.04533049
 0.00067973 0.11237844 0.13866556 0.00849202 0.14105482 0.07863046]
Step 76: Loss = -0.0020, Weights = [0.14438674 0.11796895 0.14455107 0.04206706 0.02560081 0.04552396
 0.00067157 0.11226138 0.13889211 0.00841787 0.14124975 0.07840868]
Step 77: Loss = -0.0020, Weights = [0.14453934 0.11781135 0.14469175 0.04189594 0.02543783 0.04572879
 0.00066364 0.11214729 0.13910581 0.008347   0.14143166 0.07819967]
Step 78: Loss = -0.0020, Weights = [0.14467865 0.11765669 0.14481936 0.04173611 0.02528316 0.04594412
 0.00065592 0.11203621 0.13930681 0.0082792  0.14160088 0.07800288]
Step 79: Loss = -0.0020, Weights = [0.14480542 0.11750532 0.14493473 0.04158697 0.02513633 0.04616908
 0.00064841 0.1119283  0.13949537 0.00821429 0.14175794 0.07781785]
Step 80: Loss = -0.0020, Weights = [0.14492032 0.11735761 0.1450386  0.04144792 0.02499692 0.04640285
 0.00064109 0.11182366 0.13967171 0.00815208 0.14190325 0.07764405]
Step 81: Loss = -0.0020, Weights = [0.14502408 0.11721383 0.14513169 0.04131839 0.02486448 0.04664456
 0.00063396 0.11172229 0.13983607 0.00809243 0.1420373  0.07748094]
Step 82: Loss = -0.0020, Weights = [0.14511742 0.11707419 0.14521474 0.04119785 0.02473865 0.04689341
 0.000627   0.11162422 0.13998881 0.00803516 0.14216053 0.07732806]
Step 83: Loss = -0.0020, Weights = [0.14520103 0.1169389  0.14528842 0.04108579 0.02461905 0.04714856
 0.0006202  0.11152943 0.14013019 0.00798015 0.1422734  0.07718486]
Step 84: Loss = -0.0020, Weights = [0.14527558 0.11680807 0.14535345 0.04098174 0.02450535 0.0474092
 0.00061357 0.11143793 0.14026055 0.00792726 0.14237642 0.07705086]
Step 85: Loss = -0.0020, Weights = [0.14534174 0.11668181 0.14541048 0.04088521 0.02439721 0.04767452
 0.00060708 0.11134969 0.14038025 0.00787636 0.14247006 0.07692557]
Step 86: Loss = -0.0020, Weights = [0.14540015 0.11656023 0.14546013 0.04079577 0.02429434 0.04794373
 0.00060073 0.11126464 0.14048967 0.00782735 0.1425548  0.0768085 ]
Step 87: Loss = -0.0020, Weights = [0.1454514  0.11644329 0.14550303 0.04071299 0.02419645 0.04821603
 0.00059453 0.11118266 0.1405892  0.00778011 0.14263114 0.07669917]
Step 88: Loss = -0.0020, Weights = [0.1454961  0.11633102 0.14553978 0.04063647 0.02410327 0.04849067
 0.00058845 0.11110373 0.14067928 0.00773456 0.14269951 0.07659715]
Step 89: Loss = -0.0020, Weights = [0.14553481 0.11622341 0.14557093 0.04056585 0.02401455 0.04876686
 0.00058249 0.11102775 0.14076032 0.00769059 0.14276043 0.07650198]
Step 90: Loss = -0.0020, Weights = [0.1455681  0.11612041 0.14559701 0.04050076 0.02393004 0.04904388
 0.00057666 0.1109546  0.14083278 0.00764812 0.14281438 0.07641325]
Step 91: Loss = -0.0020, Weights = [0.14559649 0.11602195 0.14561853 0.04044086 0.02384955 0.04932098
 0.00057094 0.11088418 0.14089711 0.00760707 0.1428618  0.07633054]
Step 92: Loss = -0.0020, Weights = [0.14562045 0.11592792 0.14563598 0.04038582 0.02377284 0.04959745
 0.00056533 0.1108164  0.14095381 0.00756736 0.14290318 0.07625344]
Step 93: Loss = -0.0020, Weights = [0.14564048 0.11583824 0.14564979 0.04033534 0.02369973 0.04987261
 0.00055982 0.11075116 0.14100331 0.00752893 0.14293894 0.0761816 ]
Step 94: Loss = -0.0020, Weights = [0.14565702 0.11575279 0.14566042 0.04028914 0.02363004 0.05014578
 0.00055441 0.11068834 0.14104612 0.00749172 0.1429696  0.07611462]
Step 95: Loss = -0.0020, Weights = [0.14567044 0.11567143 0.14566825 0.04024694 0.02356359 0.05041631
 0.0005491  0.11062784 0.14108272 0.00745565 0.14299554 0.07605217]
Step 96: Loss = -0.0020, Weights = [0.1456812  0.11559403 0.14567368 0.04020847 0.02350022 0.05068358
 0.00054389 0.11056956 0.14111355 0.00742069 0.1430172  0.07599393]
Step 97: Loss = -0.0020, Weights = [0.14568962 0.11552045 0.14567702 0.0401735  0.02343977 0.050947
 0.00053876 0.11051338 0.1411391  0.00738676 0.143035   0.07593958]
Step 98: Loss = -0.0020, Weights = [0.14569607 0.11545059 0.14567864 0.04014181 0.02338212 0.051206
 0.00053372 0.11045924 0.14115988 0.00735382 0.1430493  0.07588883]
Step 99: Loss = -0.0020, Weights = [0.14570084 0.11538425 0.14567879 0.04011318 0.02332711 0.05146005
 0.00052876 0.11040703 0.14117631 0.00732184 0.14306049 0.07584143]
Step 100: Loss = -0.0021, Weights = [0.14570418 0.11532129 0.1456777  0.04008739 0.02327464 0.05170863
 0.00052388 0.11035667 0.14118885 0.00729076 0.14306895 0.0757971 ]
Step 101: Loss = -0.0021, Weights = [0.1457064  0.11526155 0.1456757  0.04006426 0.02322458 0.05195129
 0.00051908 0.11030808 0.1411979  0.00726054 0.14307503 0.0757556 ]
Step 102: Loss = -0.0021, Weights = [0.1457077  0.11520492 0.14567296 0.04004362 0.02317682 0.05218759
 0.00051436 0.11026118 0.14120394 0.00723116 0.14307903 0.07571671]
Step 103: Loss = -0.0021, Weights = [0.14570832 0.11515119 0.1456697  0.0400253  0.02313127 0.05241716
 0.00050971 0.11021592 0.14120732 0.00720257 0.14308128 0.07568023]
Step 104: Loss = -0.0021, Weights = [0.14570844 0.11510029 0.14566608 0.04000914 0.02308783 0.05263961
 0.00050513 0.11017221 0.1412085  0.00717474 0.14308207 0.07564596]
Step 105: Loss = -0.0021, Weights = [0.14570822 0.11505204 0.14566222 0.03999501 0.02304641 0.05285466
 0.00050062 0.11013003 0.14120774 0.00714765 0.1430817  0.07561375]
Step 106: Loss = -0.0021, Weights = [0.14570782 0.11500631 0.14565833 0.03998277 0.02300691 0.053062
 0.00049618 0.11008929 0.14120544 0.00712126 0.14308034 0.07558341]
Step 107: Loss = -0.0021, Weights = [0.14570735 0.11496298 0.14565448 0.03997227 0.02296928 0.05326141
 0.0004918  0.11004997 0.14120188 0.00709555 0.14307825 0.0755548 ]
Step 108: Loss = -0.0021, Weights = [0.14570689 0.11492192 0.14565077 0.0399634  0.02293342 0.05345271
 0.00048749 0.11001201 0.1411974  0.00707049 0.14307562 0.0755278 ]
Step 109: Loss = -0.0021, Weights = [0.1457066  0.11488304 0.14564729 0.03995607 0.02289928 0.05363573
 0.00048324 0.10997542 0.14119227 0.00704607 0.14307265 0.0755023 ]
Step 110: Loss = -0.0021, Weights = [0.14570649 0.11484624 0.14564408 0.03995018 0.0228668  0.05381036
 0.00047904 0.10994014 0.1411867  0.00702226 0.14306955 0.07547817]
Step 111: Loss = -0.0021, Weights = [0.14570664 0.11481136 0.14564121 0.03994562 0.02283591 0.0539765
 0.00047491 0.10990616 0.14118093 0.00699904 0.14306639 0.07545534]
Step 112: Loss = -0.0021, Weights = [0.14570707 0.11477834 0.14563872 0.03994232 0.02280655 0.05413414
 0.00047084 0.10987345 0.14117512 0.00697639 0.14306334 0.0754337 ]
Step 113: Loss = -0.0021, Weights = [0.14570785 0.11474708 0.14563666 0.03994018 0.02277867 0.05428328
 0.00046682 0.10984201 0.14116949 0.0069543  0.14306049 0.07541321]
Step 114: Loss = -0.0021, Weights = [0.14570898 0.11471749 0.14563501 0.03993913 0.02275223 0.05442394
 0.00046285 0.1098118  0.14116414 0.00693275 0.1430579  0.07539379]
Step 115: Loss = -0.0021, Weights = [0.14571042 0.1146895  0.14563374 0.03993911 0.02272718 0.05455619
 0.00045894 0.10978284 0.14115922 0.00691173 0.14305572 0.07537536]
Step 116: Loss = -0.0021, Weights = [0.1457122  0.11466307 0.14563294 0.03994006 0.02270348 0.05468014
 0.00045509 0.10975512 0.14115481 0.00689122 0.14305393 0.07535791]
Step 117: Loss = -0.0021, Weights = [0.14571428 0.11463811 0.14563254 0.03994191 0.02268108 0.05479592

## Save the loss during optimization

In [14]:
loss_list = np.array(loss_list)
cos_dist_list = np.array(cos_dist_list)
np.savetxt(f"{base_dir}/AdaPro_total_loss.csv", loss_list, delimiter='\t')
np.savetxt(f"{base_dir}/AdaPro_cosine_loss.csv", cos_dist_list, delimiter='\t')

## Save the consensus weights and predictions

In [15]:
AdaPro_weights = F.softmax(alpha, dim=0).detach().cpu().numpy()
AdaPro_weights_df = pd.DataFrame(AdaPro_weights, index=base_methods, columns=["AdaPro_weight"])
AdaPro_weights_df.to_csv(f"{base_dir}/AdaPro_weights.csv")
AdaPro_weights_df

         AdaPro_weight
Babel         0.143960
cTPnet        0.114862
Dengkw        0.143905
Liger         0.042306
moETM         0.024660
sciPENN       0.055338
scMM          0.000076
scMOG         0.109961
scMoGNN       0.139419
scVAEIT       0.007298
Seurat        0.141328
TotalVI       0.076886

In [16]:
AdaPro_prediction = pd.DataFrame(sum(w * H for w, H in zip(AdaPro_weights, H_list)).detach().cpu().numpy(), index=mean_res.index, columns=mean_res.columns)
AdaPro_prediction.to_csv(f"{base_dir}/test_predicted_protein_expression (AdaPro).csv")
AdaPro_prediction

,ADT_4-1BBLigand(CD137L)_A0890,ADT_CD102_A0104,ADT_CD103_A0201,ADT_CD105_A0812,ADT_CD106_A0226,ADT_CD107a(LAMP-1)_A0905,ADT_CD115(CSF-1R)_A0105,ADT_CD117(c-Kit)_A0012,ADT_CD11a_A0595,ADT_CD11b_A0014,...,ADT_TCRVr3_A0210,ADT_TCRbchain_A0120,ADT_TCRr-d_A0121,ADT_TER-119-ErythroidCells_A0122,ADT_TIGIT(Vstm3)_A0848,ADT_TLR4(CD284)-MD2Complex_A0875,ADT_Tim-4_A0567,ADT_XCR1_A0568,ADT_anti-P2RY12_A0415,ADT_integrinb7_A0214
index,,,,,,,,,,,,,,,,,,,,,
AAACCCAAGCGATCGA-1,3.817907,4.143697,4.196487,3.836273,3.841838,3.788819,3.808467,3.934795,4.403585,3.816144,...,3.996256,4.222044,3.862307,3.620531,4.021715,3.832752,3.935245,3.822791,3.906328,4.345287
AAACCCACACCTCTAC-1,3.791790,4.256878,3.923082,3.804033,3.904397,3.809482,3.797613,3.822394,4.350668,3.825217,...,3.959751,3.811607,3.825924,3.635430,4.005447,3.789449,3.998415,3.828075,3.867786,4.095747
AAACCCACACGTCGTG-1,3.810685,4.368353,3.946653,3.831862,3.864308,3.796092,3.799678,3.834121,4.210630,3.856643,...,3.981858,3.839611,3.861253,3.632844,4.008352,3.820262,3.937443,3.830501,3.895743,4.141787
AAACCCACATGTCTAG-1,3.792098,4.328015,3.929732,3.810225,3.864941,3.799546,3.785662,3.829530,4.271659,3.833857,...,3.970244,3.810950,3.854955,3.632943,4.013797,3.814045,3.955496,3.820640,3.896291,4.134576
AAACCCAGTCAAAGTA-1,3.799362,4.256075,3.934438,3.810160,3.867351,3.813530,3.800527,3.846454,4.297073,3.834540,...,3.979129,3.834408,3.849883,3.615787,4.011728,3.800612,3.947466,3.830513,3.899673,4.184806
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TTTGTTGCATTCCTCG-1,3.786403,4.263252,3.934550,3.832594,3.865317,3.808351,3.810758,3.846072,4.270144,3.914462,...,3.977782,3.839362,3.858001,3.623211,4.016964,3.812399,3.958728,3.820159,3.899483,4.177395
TTTGTTGGTGCTCTTC-1,3.799323,4.266675,3.934314,3.825869,3.868092,3.819027,3.817139,3.854803,4.252442,3.860951,...,3.982053,3.841914,3.856089,3.607587,4.023036,3.810563,3.959390,3.823554,3.900990,4.181790
TTTGTTGTCAGCCTTC-1,3.814278,4.148173,3.928086,3.818609,3.844681,3.802485,3.826708,3.912287,4.413199,3.864571,...,4.000381,4.322999,3.852013,3.633841,4.024358,3.835100,3.948349,3.833802,3.890440,4.101065
TTTGTTGTCCCTTGGT-1,3.802292,4.163466,4.185852,3.847721,3.857086,3.800739,3.810289,3.937877,4.411244,3.816456,...,3.990596,4.206569,3.861253,3.636648,4.024374,3.825919,3.944764,3.821404,3.899225,4.333172
TTTGTTGTCTTACTGT-1,3.847460,4.241793,3.964420,3.844069,3.858695,3.825726,3.835441,3.884708,4.156133,3.813074,...,4.006725,3.884025,3.885044,3.671257,4.043993,3.844452,3.966259,3.852599,3.925938,4.108617