## Load the required packages

In [1]:
import numpy as np
import torch.nn as nn
import pandas as pd
import torch.nn.functional as F
import torch
import torch.optim as optim
from scipy import stats
import anndata
import os
from scipy.sparse import csr_matrix
from pathlib import Path

## Set path

In [2]:
working_dir = Path(os.getcwd())
dataset_dir = f"{working_dir.parents[1]}/datasets/CITE-SLN-Gayoso"
base_dir = f"{working_dir.parents[1]}/outputs/batch variation/208_M2-208_M1/cTPnet"
os.makedirs(base_dir, exist_ok=True)

## Load data

In [3]:
train_data = anndata.read(f"{dataset_dir}/SLN208_M2.h5ad")  
test_data = anndata.read(f"{dataset_dir}/SLN208_M1.h5ad")   
train_data, test_data

(AnnData object with n_obs × n_vars = 7105 × 13553
     obs: 'n_protein_counts', 'n_proteins', 'seurat_hash_id', 'batch_indices', 'hash_id', 'n_genes', 'percent_mito', 'leiden_subclusters', 'cell_types'
     var: 'gene_ids', 'feature_types', 'highly_variable', 'highly_variable_mean_variance', 'encode', 'hvg_encode'
     uns: 'protein_names', 'version'
     obsm: 'protein_expression',
 AnnData object with n_obs × n_vars = 8715 × 13553
     obs: 'n_protein_counts', 'n_proteins', 'seurat_hash_id', 'batch_indices', 'hash_id', 'n_genes', 'percent_mito', 'leiden_subclusters', 'cell_types'
     var: 'gene_ids', 'feature_types', 'highly_variable', 'highly_variable_mean_variance', 'encode', 'hvg_encode'
     uns: 'protein_names', 'version'
     obsm: 'protein_expression')

In [4]:
denoised_gene_expression_train = pd.read_table(f"{dataset_dir}/SLN208_M2_denoised_gene_expression_data.txt", index_col=0, sep=" ").T
denoised_gene_expression_test = pd.read_table(f"{dataset_dir}/SLN208_M1_denoised_gene_expression_data.txt", index_col=0, sep=" ").T
denoised_gene_expression_train, denoised_gene_expression_test

(       1      2      3      4      5      6      7      8      9      10     \
 V1     0.138  0.130  0.218  0.063  0.179  0.033  0.144  0.010  0.037  0.001
 V2     0.083  0.076  0.309  0.071  0.252  0.043  0.214  0.011  0.040  0.001
 V3     0.118  0.144  0.275  0.080  0.312  0.042  0.231  0.011  0.025  0.001
 V4     0.104  0.116  0.516  0.061  0.343  0.041  0.388  0.011  0.037  0.001
 V5     0.081  0.089  0.293  0.058  0.218  0.039  0.250  0.011  0.030  0.001
 ...      ...    ...    ...    ...    ...    ...    ...    ...    ...    ...
 V7101  0.133  0.126  0.390  0.058  0.260  0.045  0.512  0.011  0.037  0.001
 V7102  0.113  0.103  0.228  0.079  0.293  0.047  0.243  0.010  0.028  0.001
 V7103  0.120  0.146  0.251  0.100  0.405  0.068  0.294  0.011  0.029  0.001
 V7104  0.097  0.100  0.313  0.061  0.317  0.039  0.311  0.010  0.019  0.001
 V7105  0.123  0.200  0.242  0.075  0.330  0.052  0.248  0.010  0.026  0.001

        ...  13544  13545  13546  13547  13548  13549  13550  13551  13552  \
 V1     ...  0.013  0.006  0.001  0.002  0.002  0.001  0.002  0.486  0.068
 V2     ...  0.001  0.006  0.001  0.011  0.002  0.005  0.002  1.330  0.072
 V3     ...  0.012  0.006  0.001  0.003  0.002  0.001  0.002  1.719  0.071
 V4     ...  0.001  0.006  0.001  0.013  0.002  0.010  0.002  1.360  0.171
 V5     ...  0.001  0.006  0.001  0.009  0.002  0.008  0.002  1.750  0.071
 ...    ...    ...    ...    ...    ...    ...    ...    ...    ...    ...
 V7101  ...  0.002  0.006  0.001  0.030  0.002  0.021  0.002  2.688  0.072
 V7102  ...  0.008  0.006  0.001  0.002  0.002  0.001  0.002  1.336  0.070
 V7103  ...  0.013  0.006  0.001  0.004  0.002  0.001  0.002  3.844  0.073
 V7104  ...  0.001  0.006  0.001  0.049  0.002  0.011  0.002  2.157  0.071
 V7105  ...  0.016  0.006  0.001  0.003  0.002  0.001  0.002  0.633  0.069

        13553
 V1     0.001
 V2     0.001
 V3     0.001
 V4     0.001
 V5     0.001
 ...      ...
 V7101  0.001
 V7102  0.001
 V7103  0.001
 V7104  0.001
 V7105  0.001

 [7105 rows x 13553 columns],
        1      2      3      4      5      6      7      8      9      10     \
 V1     0.493  0.111  0.223  0.151  0.450  0.097  0.231  0.009  0.157  0.001
 V2     0.308  0.187  0.464  0.182  0.812  0.119  0.458  0.009  0.152  0.001
 V3     0.314  0.169  0.501  0.194  0.600  0.113  0.439  0.009  0.125  0.001
 V4     0.250  0.197  0.417  0.190  0.564  0.127  0.348  0.009  0.096  0.001
 V5     0.327  0.163  0.363  0.155  0.343  0.147  0.328  0.009  0.100  0.001
 ...      ...    ...    ...    ...    ...    ...    ...    ...    ...    ...
 V8711  0.364  0.190  0.422  0.259  0.497  0.152  0.677  0.009  0.166  0.001
 V8712  0.340  0.208  0.458  0.198  0.527  0.244  0.615  0.009  0.118  0.001
 V8713  0.442  0.158  0.399  0.290  0.740  0.155  0.286  0.009  0.228  0.001
 V8714  0.361  0.167  0.302  0.254  0.912  0.155  0.395  0.008  0.090  0.001
 V8715  0.266  0.306  0.579  0.368  1.538  0.230  1.524  0.009  0.116  0.001

        ...  13544  13545  13546  13547  13548  13549  13550  13551  13552  \
 V1     ...  0.011  0.001  0.002  0.003  0.001  0.001  0.001  1.126  0.153
 V2     ...  0.004  0.019  0.002  0.126  0.005  0.050  0.030  9.104  0.183
 V3     ...  0.003  0.006  0.002  0.016  0.006  0.032  0.003  1.387  0.175
 V4     ...  0.002  0.013  0.002  0.027  0.010  0.054  0.008  1.434  0.176
 V5     ...  0.002  0.010  0.002  0.050  0.006  0.045  0.010  2.821  0.216
 ...    ...    ...    ...    ...    ...    ...    ...    ...    ...    ...
 V8711  ...  0.002  0.004  0.002  0.015  0.008  0.031  0.008  1.902  0.214
 V8712  ...  0.005  0.010  0.002  0.060  0.010  0.041  0.010  1.928  0.230
 V8713  ...  0.025  0.002  0.002  0.003  0.001  0.002  0.002  1.050  0.205
 V8714  ...  0.017  0.002  0.002  0.006  0.001  0.001  0.001  0.717  0.116
 V8715  ...  0.011  0.013  0.002  0.160  0.028  0.051  0.021  2.403  0.151

        13553
 V1     0.004
 V2     0.004
 V3     0.004
 V4     0.004
 V5     0.004
 ...      ...
 V8711  0.004
 V8712  0.004
 V8713  0.004
 V8714  0.004
 V8715  0.004

 [8715 rows x 13553 columns])

In [5]:
denoised_gene_expression_train.index = train_data.obs.index
denoised_gene_expression_train.columns = train_data.var.index
denoised_gene_expression_test.index = test_data.obs.index
denoised_gene_expression_test.columns = test_data.var.index
denoised_gene_expression_train, denoised_gene_expression_test

(index               Mrpl15  Lypla1  Tcea1  Atp6v1h  Rb1cc1  4732440D04Rik  \
 index
 AAACCCAAGGTATCTC-2   0.138   0.130  0.218    0.063   0.179          0.033
 AAACCCACATTCTGTT-2   0.083   0.076  0.309    0.071   0.252          0.043
 AAACCCAGTAGCTTGT-2   0.118   0.144  0.275    0.080   0.312          0.042
 AAACCCAGTATCAGCT-2   0.104   0.116  0.516    0.061   0.343          0.041
 AAACCCAGTTTCTATC-2   0.081   0.089  0.293    0.058   0.218          0.039
 ...                    ...     ...    ...      ...     ...            ...
 TTTGTTGGTGGGCTCT-2   0.133   0.126  0.390    0.058   0.260          0.045
 TTTGTTGTCAAATAGG-2   0.113   0.103  0.228    0.079   0.293          0.047
 TTTGTTGTCACGAGGA-2   0.120   0.146  0.251    0.100   0.405          0.068
 TTTGTTGTCTCGACCT-2   0.097   0.100  0.313    0.061   0.317          0.039
 TTTGTTGTCTTGGTCC-2   0.123   0.200  0.242    0.075   0.330          0.052

 index               Pcmtd1  Gm26901   Rrs1  Adhfe1  ...  Tmlhe  AC133103.1  \
 index                                               ...
 AAACCCAAGGTATCTC-2   0.144    0.010  0.037   0.001  ...  0.013       0.006
 AAACCCACATTCTGTT-2   0.214    0.011  0.040   0.001  ...  0.001       0.006
 AAACCCAGTAGCTTGT-2   0.231    0.011  0.025   0.001  ...  0.012       0.006
 AAACCCAGTATCAGCT-2   0.388    0.011  0.037   0.001  ...  0.001       0.006
 AAACCCAGTTTCTATC-2   0.250    0.011  0.030   0.001  ...  0.001       0.006
 ...                    ...      ...    ...     ...  ...    ...         ...
 TTTGTTGGTGGGCTCT-2   0.512    0.011  0.037   0.001  ...  0.002       0.006
 TTTGTTGTCAAATAGG-2   0.243    0.010  0.028   0.001  ...  0.008       0.006
 TTTGTTGTCACGAGGA-2   0.294    0.011  0.029   0.001  ...  0.013       0.006
 TTTGTTGTCTCGACCT-2   0.311    0.010  0.019   0.001  ...  0.001       0.006
 TTTGTTGTCTTGGTCC-2   0.248    0.010  0.026   0.001  ...  0.016       0.006

 index               AC132444.1  Csprs  AC132444.6  AC125149.3  AC168977.1  \
 index
 AAACCCAAGGTATCTC-2       0.001  0.002       0.002       0.001       0.002
 AAACCCACATTCTGTT-2       0.001  0.011       0.002       0.005       0.002
 AAACCCAGTAGCTTGT-2       0.001  0.003       0.002       0.001       0.002
 AAACCCAGTATCAGCT-2       0.001  0.013       0.002       0.010       0.002
 AAACCCAGTTTCTATC-2       0.001  0.009       0.002       0.008       0.002
 ...                        ...    ...         ...         ...         ...
 TTTGTTGGTGGGCTCT-2       0.001  0.030       0.002       0.021       0.002
 TTTGTTGTCAAATAGG-2       0.001  0.002       0.002       0.001       0.002
 TTTGTTGTCACGAGGA-2       0.001  0.004       0.002       0.001       0.002
 TTTGTTGTCTCGACCT-2       0.001  0.049       0.002       0.011       0.002
 TTTGTTGTCTTGGTCC-2       0.001  0.003       0.002       0.001       0.002

 index                PISD  DHRSX  CAAA01147332.1
 index
 AAACCCAAGGTATCTC-2  0.486  0.068           0.001
 AAACCCACATTCTGTT-2  1.330  0.072           0.001
 AAACCCAGTAGCTTGT-2  1.719  0.071           0.001
 AAACCCAGTATCAGCT-2  1.360  0.171           0.001
 AAACCCAGTTTCTATC-2  1.750  0.071           0.001
 ...                   ...    ...             ...
 TTTGTTGGTGGGCTCT-2  2.688  0.072           0.001
 TTTGTTGTCAAATAGG-2  1.336  0.070           0.001
 TTTGTTGTCACGAGGA-2  3.844  0.073           0.001
 TTTGTTGTCTCGACCT-2  2.157  0.071           0.001
 TTTGTTGTCTTGGTCC-2  0.633  0.069           0.001

 [7105 rows x 13553 columns],
 index               Mrpl15  Lypla1  Tcea1  Atp6v1h  Rb1cc1  4732440D04Rik  \
 index
 AAACCCAAGCGATCGA-1   0.493   0.111  0.223    0.151   0.450          0.097
 AAACCCACACCTCTAC-1   0.308   0.187  0.464    0.182   0.812          0.119
 AAACCCACACGTCGTG-1   0.314   0.169  0.501    0.194   0.600          0.113
 AAACCCACATGTCTAG-1   0.250   0.197  0.417    0.190   0.564          0.127
 AAACCCAGTCAAAGTA-1   0.327   0.163  0.363    0.155   0.343          0.147
 ...                    ...     ...    ...      ...     ...            ...
 TTTGTTGCATTCCTCG-1   0.364   0.190  0.422    0.259   0.497          0.152
 TTTGTTGGTGCTCTTC-1   0.340   0.208  0.458    0.198   0.527          0.244
 TTTGTTGTCAGCCTTC-1   0.442   0.158  0.399    0.290   0.740          0.155
 TTTGTTGTCCCTTGGT-1   0.361   0.167  0.302    0.254   0.912          0.155
 TTTGTTGTCTTACTGT-1   0.266   0.306  0.579    0.368   1.538          0.230

 index               Pcmtd1  Gm26901   Rrs1  Adhfe1  ...  Tmlhe  AC133103.1  \
 index                                               ...
 AAACCCAAGCGATCGA-1   0.231    0.009  0.157   0.001  ...  0.011       0.001
 AAACCCACACCTCTAC-1   0.458    0.009  0.152   0.001  ...  0.004       0.019
 AAACCCACACGTCGTG-1   0.439    0.009  0.125   0.001  ...  0.003       0.006
 AAACCCACATGTCTAG-1   0.348    0.009  0.096   0.001  ...  0.002       0.013
 AAACCCAGTCAAAGTA-1   0.328    0.009  0.100   0.001  ...  0.002       0.010
 ...                    ...      ...    ...     ...  ...    ...         ...
 TTTGTTGCATTCCTCG-1   0.677    0.009  0.166   0.001  ...  0.002       0.004
 TTTGTTGGTGCTCTTC-1   0.615    0.009  0.118   0.001  ...  0.005       0.010
 TTTGTTGTCAGCCTTC-1   0.286    0.009  0.228   0.001  ...  0.025       0.002
 TTTGTTGTCCCTTGGT-1   0.395    0.008  0.090   0.001  ...  0.017       0.002
 TTTGTTGTCTTACTGT-1   1.524    0.009  0.116   0.001  ...  0.011       0.013

 index               AC132444.1  Csprs  AC132444.6  AC125149.3  AC168977.1  \
 index
 AAACCCAAGCGATCGA-1       0.002  0.003       0.001       0.001       0.001
 AAACCCACACCTCTAC-1       0.002  0.126       0.005       0.050       0.030
 AAACCCACACGTCGTG-1       0.002  0.016       0.006       0.032       0.003
 AAACCCACATGTCTAG-1       0.002  0.027       0.010       0.054       0.008
 AAACCCAGTCAAAGTA-1       0.002  0.050       0.006       0.045       0.010
 ...                        ...    ...         ...         ...         ...
 TTTGTTGCATTCCTCG-1       0.002  0.015       0.008       0.031       0.008
 TTTGTTGGTGCTCTTC-1       0.002  0.060       0.010       0.041       0.010
 TTTGTTGTCAGCCTTC-1       0.002  0.003       0.001       0.002       0.002
 TTTGTTGTCCCTTGGT-1       0.002  0.006       0.001       0.001       0.001
 TTTGTTGTCTTACTGT-1       0.002  0.160       0.028       0.051       0.021

 index                PISD  DHRSX  CAAA01147332.1
 index
 AAACCCAAGCGATCGA-1  1.126  0.153           0.004
 AAACCCACACCTCTAC-1  9.104  0.183           0.004
 AAACCCACACGTCGTG-1  1.387  0.175           0.004
 AAACCCACATGTCTAG-1  1.434  0.176           0.004
 AAACCCAGTCAAAGTA-1  2.821  0.216           0.004
 ...                   ...    ...             ...
 TTTGTTGCATTCCTCG-1  1.902  0.214           0.004
 TTTGTTGGTGCTCTTC-1  1.928  0.230           0.004
 TTTGTTGTCAGCCTTC-1  1.050  0.205           0.004
 TTTGTTGTCCCTTGGT-1  0.717  0.116           0.004
 TTTGTTGTCTTACTGT-1  2.403  0.151           0.004

 [8715 rows x 13553 columns])

## Select common genes

In [6]:
common_genes = np.intersect1d(train_data.var.index, test_data.var.index)
train_data.X = denoised_gene_expression_train.loc[:, common_genes]
test_data.X = denoised_gene_expression_test.loc[:, common_genes]

## Select common proteins

In [7]:
common_proteins = np.intersect1d(np.array(train_data.uns["protein_names"]), np.array(test_data.uns["protein_names"]))
if isinstance(train_data.obsm["protein_expression"], pd.DataFrame):
    train_protein_expression = train_data.obsm["protein_expression"]
    train_protein_expression = train_protein_expression.loc[:, common_proteins]
    train_data.obsm["protein_expression"] = train_protein_expression
    train_data.uns["protein_names"] = np.array(train_protein_expression.columns)
else:
    train_protein_expression = pd.DataFrame(train_data.obsm["protein_expression"].todense(), index=train_data.obs.index, columns=train_data.uns["protein_names"])
    train_protein_expression = train_protein_expression.loc[:, common_proteins]
    train_data.obsm["protein_expression"] = csr_matrix(train_protein_expression.values)
    train_data.uns["protein_names"] = np.array(train_protein_expression.columns)

if isinstance(test_data.obsm["protein_expression"], pd.DataFrame):
    test_protein_expression = test_data.obsm["protein_expression"]
    test_protein_expression = test_protein_expression.loc[:, common_proteins]
    test_data.obsm["protein_expression"] = test_protein_expression
    test_data.uns["protein_names"] = np.array(test_protein_expression.columns)
else:
    test_protein_expression = pd.DataFrame(test_data.obsm["protein_expression"].todense(), index=test_data.obs.index, columns=test_data.uns["protein_names"])
    test_protein_expression = test_protein_expression.loc[:, common_proteins]
    test_data.obsm["protein_expression"] = csr_matrix(test_protein_expression.values)
    test_data.uns["protein_names"] = np.array(test_protein_expression.columns)

In [8]:
gene_list = list(set(train_data.var.index.tolist()))
gene_list.sort()
X = train_data.to_df().loc[:, gene_list]   
x_batch2 = test_data.to_df().loc[:, gene_list]

In [9]:
protein_list = list(set(train_data.uns["protein_names"]))
y = train_protein_expression.loc[X.index, protein_list]

## Replace '.' with '/' for PyTorch and record the mapping

In [10]:
if any("." in item for item in protein_list):
    protein_names_convert = pd.DataFrame({"original_name": protein_list})
    protein_list = [item.replace('.', '/') for item in protein_list]
    protein_names_convert["convert_name"] = protein_list
    protein_names_convert.to_csv(f"{base_dir}/cTPnet_protein_names_convert.csv")
protein_names_convert

                original_name              convert_name
0    ADT_CD339(Jagged1)_A0887  ADT_CD339(Jagged1)_A0887
1       ADT_CD272(BTLA)_A0881     ADT_CD272(BTLA)_A0881
2              ADT_ESAM_A0596            ADT_ESAM_A0596
3              ADT_CD63_A0559            ADT_CD63_A0559
4        ADT_CD200(OX2)_A0079      ADT_CD200(OX2)_A0079
..                        ...                       ...
193            ADT_CD83_A0562            ADT_CD83_A0562
194     ADT_CD26(DPP-4)_A0883     ADT_CD26(DPP-4)_A0883
195           ADT_ENPP1_A0891           ADT_ENPP1_A0891
196     ADT_CD150(SLAM)_A0203     ADT_CD150(SLAM)_A0203
197      ADT_CD155(PVR)_A1011      ADT_CD155(PVR)_A1011

[198 rows x 2 columns]

## Normalize reference raw gene and protein expression

In [11]:
X = X.apply(lambda x: np.log((x * 10000.0 / sum(x)) + 1.0), axis=1)   
y = y.apply(lambda x: np.log((x + 1.0) / stats.gmean(x + 1.0)), axis=1)   
X, y

(index               0610007P14Rik  0610009B22Rik  0610009L18Rik  \
 index
 AAACCCAAGGTATCTC-2       0.421835       0.471478       2.961442
 AAACCCACATTCTGTT-2       0.437466       0.537453       2.490818
 AAACCCAGTAGCTTGT-2       0.436213       0.336299       2.785374
 AAACCCAGTATCAGCT-2       0.510199       0.343316       2.447741
 AAACCCAGTTTCTATC-2       0.501419       0.529970       2.548012
 ...                           ...            ...            ...
 TTTGTTGGTGGGCTCT-2       0.477034       0.314193       2.493733
 TTTGTTGTCAAATAGG-2       0.358082       0.347274       2.686135
 TTTGTTGTCACGAGGA-2       0.325289       0.427981       2.342618
 TTTGTTGTCTCGACCT-2       0.420162       0.320465       2.573154
 TTTGTTGTCTTGGTCC-2       0.373719       0.395944       2.651654

 index               0610009O20Rik  0610010F05Rik  0610010K14Rik  \
 index
 AAACCCAAGGTATCTC-2       0.003689       0.108459       0.029135
 AAACCCACATTCTGTT-2       0.010565       0.243855       0.017548
 AAACCCAGTAGCTTGT-2       0.003764       0.120645       0.033378
 AAACCCAGTATCAGCT-2       0.032385       0.155494       0.025279
 AAACCCAGTTTCTATC-2       0.018225       0.130832       0.018225
 ...                           ...            ...            ...
 TTTGTTGGTGGGCTCT-2       0.023537       0.187648       0.046533
 TTTGTTGTCAAATAGG-2       0.007660       0.152990       0.048770
 TTTGTTGTCACGAGGA-2       0.023990       0.207550       0.058929
 TTTGTTGTCTCGACCT-2       0.007380       0.227573       0.029198
 TTTGTTGTCTTGGTCC-2       0.008131       0.144209       0.047825

 index               0610011F06Rik  0610012G03Rik  0610030E20Rik  \
 index
 AAACCCAAGGTATCTC-2       0.007364       0.060929       0.221219
 AAACCCACATTCTGTT-2       0.003534       0.061781       0.075006
 AAACCCAGTAGCTTGT-2       0.022376       0.065679       0.191606
 AAACCCAGTATCAGCT-2       0.003651       0.358763       0.073996
 AAACCCAGTTTCTATC-2       0.003672       0.064110       0.064110
 ...                           ...            ...            ...
 TTTGTTGGTGGGCTCT-2       0.003962       0.069012       0.069012
 TTTGTTGTCAAATAGG-2       0.007660       0.363442       0.213787
 TTTGTTGTCACGAGGA-2       0.027933       0.070309       0.197636
 TTTGTTGTCTCGACCT-2       0.003697       0.064537       0.091935
 TTTGTTGTCTTGGTCC-2       0.040011       0.067096       0.248168

 index               0610037L13Rik  ...    mt-Co2    mt-Co3   mt-Cytb  \
 index                              ...
 AAACCCAAGGTATCTC-2       0.557605  ...  0.218252  0.374691  1.819692
 AAACCCACATTCTGTT-2       0.061781  ...  0.104140  0.189702  2.242762
 AAACCCAGTAGCTTGT-2       0.414026  ...  0.260773  0.481495  2.322211
 AAACCCAGTATCAGCT-2       0.100805  ...  0.113945  0.242393  2.213179
 AAACCCAGTTTCTATC-2       0.081213  ...  0.114564  0.266433  2.412293
 ...                           ...  ...       ...       ...       ...
 TTTGTTGGTGGGCTCT-2       0.119578  ...  0.210419  0.370558  2.734174
 TTTGTTGTCAAATAGG-2       0.418056  ...  0.244359  0.366112  2.099995
 TTTGTTGTCACGAGGA-2       0.549532  ...  0.295624  0.551865  2.400033
 TTTGTTGTCTCGACCT-2       0.091935  ...  0.138147  0.215704  2.427071
 TTTGTTGTCTTGGTCC-2       0.550894  ...  0.285676  0.519826  2.220223

 index                 mt-Nd1    mt-Nd2    mt-Nd3    mt-Nd4   mt-Nd4l  \
 index
 AAACCCAAGGTATCTC-2  0.134639  0.101806  0.605125  0.503256  0.496531
 AAACCCACATTCTGTT-2  0.212862  0.100944  0.473389  0.656282  0.529144
 AAACCCAGTAGCTTGT-2  0.292234  0.107184  0.370725  0.765582  0.436213
 AAACCCAGTATCAGCT-2  0.270690  0.104106  0.270690  0.363860  0.376489
 AAACCCAGTTTCTATC-2  0.217342  0.104675  0.217342  0.342379  0.545012
 ...                      ...       ...       ...       ...       ...
 TTTGTTGGTGGGCTCT-2  0.317088  0.112509  0.370558  0.712942  0.520422
 TTTGTTGTCAAATAGG-2  0.156283  0.109155  0.752637  0.479408  0.430631
 TTTGTTGTCACGAGGA-2  0.233515  0.114577  0.659991  0.700970  0.535418
 TTTGTTGTCTCGACCT-2  0.306933  0.105358  0.407923  0.508591  0.506361
 TTTGTTGTCTTGGTCC-2  0.232114  0.111886  0.627861  0.612492  0.514959

 index                 mt-Nd5    mt-Nd6
 index
 AAACCCAAGGTATCTC-2  0.144282  4.234754
 AAACCCACATTCTGTT-2  0.144777  4.316308
 AAACCCAGTAGCTTGT-2  0.150285  4.124710
 AAACCCAGTATCAGCT-2  0.149213  4.499725
 AAACCCAGTTTCTATC-2  0.150010  4.674873
 ...                      ...       ...
 TTTGTTGGTGGGCTCT-2  0.160973  4.696682
 TTTGTTGTCAAATAGG-2  0.152990  4.649089
 TTTGTTGTCACGAGGA-2  0.163862  4.773806
 TTTGTTGTCTCGACCT-2  0.147778  4.385237
 TTTGTTGTCTTGGTCC-2  0.161725  4.574438

 [7105 rows x 13553 columns],
                     ADT_CD339(Jagged1)_A0887  ADT_CD272(BTLA)_A0881  \
 index
 AAACCCAAGGTATCTC-2                  0.669195              -0.342406
 AAACCCACATTCTGTT-2                  1.113458               0.995675
 AAACCCAGTAGCTTGT-2                  1.130544              -1.702669
 AAACCCAGTATCAGCT-2                  1.220910               0.122298
 AAACCCAGTTTCTATC-2                  0.713750               1.088443
 ...                                      ...                    ...
 TTTGTTGGTGGGCTCT-2                  0.753321              -0.035136
 TTTGTTGTCAAATAGG-2                  0.574708              -0.523904
 TTTGTTGTCACGAGGA-2                  0.626678               0.038891
 TTTGTTGTCTCGACCT-2                  1.376841               0.817225
 TTTGTTGTCTTGGTCC-2                  0.844222              -0.254390

                     ADT_ESAM_A0596  ADT_CD63_A0559  ADT_CD200(OX2)_A0079  \
 index
 AAACCCAAGGTATCTC-2       -0.342406        0.669195              0.217210
 AAACCCACATTCTGTT-2        0.014846        0.168997              2.230420
 AAACCCAGTAGCTTGT-2        0.243241        0.599916              0.494556
 AAACCCAGTATCAGCT-2        0.276449       -0.060024              0.728434
 AAACCCAGTTTCTATC-2       -1.684146       -0.585533              1.534730
 ...                            ...             ...                   ...
 TTTGTTGGTGGGCTCT-2       -0.035136       -0.035136              0.753321
 TTTGTTGTCAAATAGG-2       -0.013079        0.456925              0.169243
 TTTGTTGTCACGAGGA-2       -0.184252        0.732038              0.375363
 TTTGTTGTCTCGACCT-2       -0.281387       -0.974534              0.411760
 TTTGTTGTCTTGGTCC-2        0.438757        0.556540              0.305225

                     ADT_CD197(CCR7)_A0377  ADT_CD2_A0892  ADT_PIR-A-B_A0882  \
 index
 AAACCCAAGGTATCTC-2               0.217210       2.653327          -0.119262
 AAACCCACATTCTGTT-2              -1.083766       2.135110           0.302528
 AAACCCAGTAGCTTGT-2               0.243241       2.531438          -0.093231
 AAACCCAGTATCAGCT-2              -0.570849       1.941456           0.122298
 AAACCCAGTTTCTATC-2              -0.297851       2.564350           0.713750
 ...                                   ...            ...                ...
 TTTGTTGGTGGGCTCT-2               0.147185       2.699231           0.301336
 TTTGTTGTCAAATAGG-2               0.169243       2.759510           0.169243
 TTTGTTGTCACGAGGA-2               0.038891       1.895189          -0.184252
 TTTGTTGTCTCGACCT-2               0.529543       1.798055           0.278229
 TTTGTTGTCTTGGTCC-2               0.438757       2.518198          -0.254390

                     ADT_CD278(ICOS)_A0171  ADT_CD273(B7-DC_PD-L2)_A0914  ...  \
 index                                                                    ...
 AAACCCAAGGTATCTC-2               0.350742                     -0.630088  ...
 AAACCCACATTCTGTT-2               0.525672                     -1.776913  ...
 AAACCCAGTAGCTTGT-2               0.695226                     -0.316375  ...
 AAACCCAGTATCAGCT-2              -0.060024                     -0.976314  ...
 AAACCCAGTTTCTATC-2              -0.585533                     -0.585533  ...
 ...                                   ...                           ...  ...
 TTTGTTGGTGGGCTCT-2               0.147185                     -0.545962  ...
 TTTGTTGTCAAATAGG-2               0.456925                     -1.622516  ...
 TTTGTTGTCACGAGGA-2               0.626678                     -1.570547  ...
 TTTGTTGTCTCGACCT-2               0.529543                     -0.058243  ...
 TTTGTTGTCTTGGTCC-2               0.924264                     -0.542073  ...

                     ADT_CD371(CLEC12A)_A0825  ADT_CD106_A0226  \
 index
 AAACCCAAGGTATCTC-2                 -1.035553        -1.035553
 AAACCCACATTCTGTT-2                  0.707993         0.014846
 AAACCCAGTAGCTTGT-2                 -1.702669        -1.009522
 AAACCCAGTATCAGCT-2                 -0.570849        -0.283167
 AAACCCAGTTTCTATC-2                  0.880804        -0.585533
 ...                                      ...              ...
 TTTGTTGGTGGGCTCT-2                  0.147185        -0.035136
 TTTGTTGTCAAATAGG-2                 -0.929369        -0.013079
 TTTGTTGTCACGAGGA-2                 -0.877400        -1.570547
 TTTGTTGTCTCGACCT-2                 -0.058243         0.278229
 TTTGTTGTCTTGGTCC-2                 -1.640685        -0.254390

                     ADT_CD1d(CD1.1_Ly-38)_A0851  ADT_FceRIa_A0115  \
 index
 AAACCCAAGGTATCTC-2                     0.836249         -1.035553
 AAACCCACATTCTGTT-2                     1.314129         -0.390619
 AAACCCAGTAGCTTGT-2                     0.376773         -0.604057
 AAACCCAGTATCAGCT-2                     0.276449         -0.570849
 AAACCCAGTTTCTATC-2                     0.618440         -1.684146
 ...                                         ...               ...
 TTTGTTGGTGGGCTCT-2                     0.840332         -0.258280
 TTTGTTGTCAAATAGG-2                     0.456925         -0.013079
 TTTGTTGTCACGAGGA-2                     0.508895         -0.471934
 TTTGTTGTCTCGACCT-2                     1.423361         -0.281387
 TTTGTTGTCTTGGTCC-2                     0.151075         -1.640685

                     ADT_PLZF_A0878  ADT_CD83_A0562  ADT_CD26(DPP-4)_A0883  \
 index
 AAACCCAAGGTATCTC-2        0.063059       -1.728700               1.603505
 AAACCCACATTCTGTT-2       -1.776913       -1.776913               1.267609
 AAACCCAGTAGCTTGT-2        0.376773       -1.009522               1.187703
 AAACCCAGTATCAGCT-2       -0.570849       -1.669461               1.549414
 AAACCCAGTTTCTATC-2       -0.297851       -0.990998               1.360377
 ...                            ...             ...                    ...
 TTTGTTGGTGGGCTCT-2       -0.545962       -0.951427               1.613522
 TTTGTTGTCAAATAGG-2       -0.523904       -1.622516               1.744779
 TTTGTTGTCACGAGGA-2       -0.471934       -1.570547               1.564947
 TTTGTTGTCTCGACCT-2       -0.281387       -1.667681               1.104908
 TTTGTTGTCTTGGTCC-2       -0.947538       -0.947538               1.403838

                     ADT_ENPP1_A0891  ADT_CD150(SLAM)_A0203  \
 index
 AAACCCAAGGTATCTC-2        -0.342406               0.573885
 AAACCCACATTCTGTT-2         0.420311               0.931137
 AAACCCAGTAGCTTGT-2         0.782238               0.936388
 AAACCCAGTATCAGCT-2         0.633124               0.895488
 AAACCCAGTTTCTATC-2         0.800761               1.749842
 ...                             ...                    ...
 TTTGTTGGTGGGCTCT-2         0.301336               1.533479
 TTTGTTGTCAAATAGG-2         0.169243               0.942433
 TTTGTTGTCACGAGGA-2        -0.184252               0.732038
 TTTGTTGTCTCGACCT-2         0.124078               0.411760
 TTTGTTGTCTTGGTCC-2         0.438757               1.249687

                     ADT_CD155(PVR)_A1011
 index
 AAACCCAAGGTATCTC-2              0.350742
 AAACCCACATTCTGTT-2             -0.390619
 AAACCCAGTAGCTTGT-2              0.599916
 AAACCCAGTATCAGCT-2             -0.060024
 AAACCCAGTTTCTATC-2             -0.585533
 ...                                  ...
 TTTGTTGGTGGGCTCT-2             -0.545962
 TTTGTTGTCAAATAGG-2             -0.236222
 TTTGTTGTCACGAGGA-2              0.038891
 TTTGTTGTCTCGACCT-2              0.124078
 TTTGTTGTCTTGGTCC-2              0.757210

 [7105 rows x 198 columns])

## Randomly select 15% of reference cells as validation set

In [12]:
X = X.sample(frac=1, random_state=4905)   
X_test = X.sample(frac=0.15, random_state=4905)   
y_test = y.loc[X_test.index, :] 
X_test, y_test

(index               0610007P14Rik  0610009B22Rik  0610009L18Rik  \
 index
 ACAAGCTCAGTTGAAA-2       0.446054       0.456211       2.262125
 ACCAACAGTAATGATG-2       0.156092       0.358875       2.764660
 GGGTAGATCACTGATG-2       0.539065       0.476321       2.305048
 TTGTTCACATGCGGTC-2       0.217863       0.325080       2.883649
 ATCCACCTCGTGTCAA-2       0.404903       0.293960       1.553570
 ...                           ...            ...            ...
 AGGCATTAGTTGGCGA-2       0.569470       0.636631       2.583740
 TGTAAGCAGGGATGTC-2       0.335842       0.316824       3.052788
 TCGATTTAGTCATCGT-2       0.442346       0.536774       2.623572
 TTGGGATCATCTAGAC-2       0.638956       0.962203       2.301170
 CAGAGCCGTAGGGAGG-2       0.417374       0.673065       2.611140

 index               0610009O20Rik  0610010F05Rik  0610010K14Rik  \
 index
 ACAAGCTCAGTTGAAA-2       0.552479       0.120071       0.027525
 ACCAACAGTAATGATG-2       0.003747       0.079356       0.029590
 GGGTAGATCACTGATG-2       0.481106       0.156929       0.034164
 TTGTTCACATGCGGTC-2       0.003796       0.076842       0.033658
 ATCCACCTCGTGTCAA-2       0.119301       0.259016       0.059622
 ...                           ...            ...            ...
 AGGCATTAGTTGGCGA-2       0.261794       0.169033       0.048672
 TGTAAGCAGGGATGTC-2       0.003758       0.113765       0.044192
 TCGATTTAGTCATCGT-2       0.011214       0.175395       0.014925
 TTGGGATCATCTAGAC-2       0.047850       0.282739       0.063305
 CAGAGCCGTAGGGAGG-2       0.015812       0.184988       0.091325

 index               0610011F06Rik  0610012G03Rik  0610030E20Rik  \
 index
 ACAAGCTCAGTTGAAA-2       0.003979       0.069304       0.035252
 ACCAACAGTAATGATG-2       0.007480       0.061866       0.209250
 GGGTAGATCACTGATG-2       0.003854       0.067200       0.059953
 TTGTTCACATGCGGTC-2       0.015099       0.066219       0.199339
 ATCCACCTCGTGTCAA-2       0.003832       0.070415       0.048710
 ...                           ...            ...            ...
 AGGCATTAGTTGGCGA-2       0.003829       0.066779       0.081033
 TGTAAGCAGGGATGTC-2       0.003758       0.062044       0.254585
 TCGATTTAGTCATCGT-2       0.003752       0.065474       0.058407
 TTGGGATCATCTAGAC-2       0.008136       0.067132       0.161807
 CAGAGCCGTAGGGAGG-2       0.007937       0.069264       0.116463

 index               0610037L13Rik  ...    mt-Co2    mt-Co3   mt-Cytb  \
 index                              ...
 ACAAGCTCAGTTGAAA-2       0.084074  ...  0.116529  0.303671  2.601105
 ACCAACAGTAATGATG-2       0.500445  ...  0.215322  0.310528  2.462077
 GGGTAGATCACTGATG-2       0.156929  ...  0.119944  0.286758  2.607266
 TTGTTCACATGCGGTC-2       0.458637  ...  0.202450  0.265644  2.191123
 ATCCACCTCGTGTCAA-2       0.088150  ...  0.216642  0.495443  2.864121
 ...                           ...  ...       ...       ...       ...
 AGGCATTAGTTGGCGA-2       0.095086  ...  0.132743  0.258837  2.580549
 TGTAAGCAGGGATGTC-2       0.327736  ...  0.239882  0.257499  2.255060
 TCGATTTAGTCATCGT-2       0.051290  ...  0.113590  0.233601  2.203827
 TTGGGATCATCTAGAC-2       0.179029  ...  0.264095  0.362585  2.166986
 CAGAGCCGTAGGGAGG-2       0.412111  ...  0.332503  0.335356  2.564411

 index                 mt-Nd1    mt-Nd2    mt-Nd3    mt-Nd4   mt-Nd4l  \
 index
 ACAAGCTCAGTTGAAA-2  0.288849  0.112975  0.178441  0.321173  0.478693
 ACCAACAGTAATGATG-2  0.152875  0.103340  0.419905  0.446678  0.366711
 GGGTAGATCACTGATG-2  0.245326  0.109616  0.211524  0.272157  0.481106
 TTGTTCACATGCGGTC-2  0.161230  0.108048  0.421907  0.429361  0.373356
 ATCCACCTCGTGTCAA-2  0.593421  0.112462  0.285338  0.836957  0.864830
 ...                      ...       ...       ...       ...       ...
 AGGCATTAGTTGGCGA-2  0.188286  0.261794  0.407198  0.402078  0.520533
 TGTAAGCAGGGATGTC-2  0.117120  0.107021  0.619759  0.447752  0.375416
 TCGATTTAGTCATCGT-2  0.191044  0.106856  0.473263  0.351378  0.321847
 TTGGGATCATCTAGAC-2  0.235461  0.115589  1.600151  0.539287  0.567470
 CAGAGCCGTAGGGAGG-2  0.161534  0.112910  1.154202  0.458513  0.443284

 index                 mt-Nd5    mt-Nd6
 index
 ACAAGCTCAGTTGAAA-2  0.161624  4.743839
 ACCAACAGTAATGATG-2  0.149648  4.495522
 GGGTAGATCACTGATG-2  0.156929  4.274682
 TTGTTCACATGCGGTC-2  0.151472  4.323182
 ATCCACCTCGTGTCAA-2  0.159381  4.917885
 ...                      ...       ...
 AGGCATTAGTTGGCGA-2  0.152700  4.796954
 TGTAAGCAGGGATGTC-2  0.150062  4.515084
 TCGATTTAGTCATCGT-2  0.153067  4.540547
 TTGGGATCATCTAGAC-2  0.161807  4.649156
 CAGAGCCGTAGGGAGG-2  0.161534  4.531822

 [1066 rows x 13553 columns],
                     ADT_CD339(Jagged1)_A0887  ADT_CD272(BTLA)_A0881  \
 index
 ACAAGCTCAGTTGAAA-2                  0.925633               0.440125
 ACCAACAGTAATGATG-2                  0.754919              -0.120550
 GGGTAGATCACTGATG-2                  0.668526               0.311851
 TTGTTCACATGCGGTC-2                  0.408196               0.274664
 ATCCACCTCGTGTCAA-2                  0.455211               0.301060
 ...                                      ...                    ...
 AGGCATTAGTTGGCGA-2                  0.534235               0.128770
 TGTAAGCAGGGATGTC-2                  0.542766              -0.438064
 TCGATTTAGTCATCGT-2                  1.077369               1.077369
 TTGGGATCATCTAGAC-2                  0.685481               0.154853
 CAGAGCCGTAGGGAGG-2                  0.712941              -0.385671

                     ADT_ESAM_A0596  ADT_CD63_A0559  ADT_CD200(OX2)_A0079  \
 index
 ACAAGCTCAGTTGAAA-2        0.152443       -0.253022              0.152443
 ACCAACAGTAATGATG-2       -0.120550        0.349454              0.061772
 GGGTAGATCACTGATG-2       -0.535447       -0.024621              1.361673
 TTGTTCACATGCGGTC-2       -0.572634        0.525979              0.525979
 ATCCACCTCGTGTCAA-2       -0.392087        0.118739              1.217351
 ...                            ...             ...                   ...
 AGGCATTAGTTGGCGA-2       -0.969843       -0.276695              0.976068
 TGTAAGCAGGGATGTC-2       -1.536676        0.255084              0.542766
 TCGATTTAGTCATCGT-2       -0.101286        0.591861              0.997326
 TTGGGATCATCTAGAC-2       -0.355973        0.154853              0.943310
 CAGAGCCGTAGGGAGG-2       -0.673353       -0.385671              0.019794

                     ADT_CD197(CCR7)_A0377  ADT_CD2_A0892  ADT_PIR-A-B_A0882  \
 index
 ACAAGCTCAGTTGAAA-2              -0.946169       1.887044           0.152443
 ACCAACAGTAATGATG-2              -0.343694       2.221256           0.215922
 GGGTAGATCACTGATG-2               0.563166       2.103611           0.311851
 TTGTTCACATGCGGTC-2              -0.284951       2.455889          -0.978099
 ATCCACCTCGTGTCAA-2              -0.392087       1.841505           0.706525
 ...                                   ...            ...                ...
 AGGCATTAGTTGGCGA-2               0.128770       2.000572           1.109599
 TGTAAGCAGGGATGTC-2              -0.150381       2.313472          -0.843529
 TCGATTTAGTCATCGT-2               0.458330       2.250089           0.709644
 TTGGGATCATCTAGAC-2               0.049492       2.056960           0.491325
 CAGAGCCGTAGGGAGG-2               0.530620      -0.162527           0.425259

                     ADT_CD278(ICOS)_A0171  ADT_CD273(B7-DC_PD-L2)_A0914  ...  \
 index                                                                    ...
 ACAAGCTCAGTTGAAA-2               0.440125                     -0.253022  ...
 ACCAACAGTAATGATG-2               0.467237                     -0.343694  ...
 GGGTAGATCACTGATG-2               0.157701                     -0.535447  ...
 TTGTTCACATGCGGTC-2               0.631339                     -0.978099  ...
 ATCCACCTCGTGTCAA-2               0.301060                     -0.797552  ...
 ...                                   ...                           ...  ...
 AGGCATTAGTTGGCGA-2               0.416452                     -0.564378  ...
 TGTAAGCAGGGATGTC-2               0.660549                     -0.843529  ...
 TCGATTTAGTCATCGT-2              -0.794433                     -0.388968  ...
 TTGGGATCATCTAGAC-2               2.026655                     -0.538294  ...
 CAGAGCCGTAGGGAGG-2               1.118407                     -0.385671  ...

                     ADT_CD371(CLEC12A)_A0825  ADT_CD106_A0226  \
 index
 ACAAGCTCAGTTGAAA-2                 -1.639316        -0.253022
 ACCAACAGTAATGATG-2                 -1.036841        -0.631376
 GGGTAGATCACTGATG-2                  0.157701        -0.535447
 TTGTTCACATGCGGTC-2                 -0.284951        -0.284951
 ATCCACCTCGTGTCAA-2                  0.301060         0.455211
 ...                                      ...              ...
 AGGCATTAGTTGGCGA-2                  0.416452        -0.053552
 TGTAAGCAGGGATGTC-2                 -1.536676        -0.843529
 TCGATTTAGTCATCGT-2                 -0.101286        -0.794433
 TTGGGATCATCTAGAC-2                 -0.201822        -0.538294
 CAGAGCCGTAGGGAGG-2                  0.173945        -1.078818

                     ADT_CD1d(CD1.1_Ly-38)_A0851  ADT_FceRIa_A0115  \
 index
 ACAAGCTCAGTTGAAA-2                     1.727980         -0.540704
 ACCAACAGTAATGATG-2                     0.667907         -0.120550
 GGGTAGATCACTGATG-2                     1.698146         -0.940912
 TTGTTCACATGCGGTC-2                     0.120514          0.274664
 ATCCACCTCGTGTCAA-2                     0.301060         -0.392087
 ...                                         ...               ...
 AGGCATTAGTTGGCGA-2                     1.770997         -0.564378
 TGTAAGCAGGGATGTC-2                     0.072762         -0.150381
 TCGATTTAGTCATCGT-2                     1.077369         -0.388968
 TTGGGATCATCTAGAC-2                     0.896790         -0.538294
 CAGAGCCGTAGGGAGG-2                     0.530620         -1.078818

                     ADT_PLZF_A0878  ADT_CD83_A0562  ADT_CD26(DPP-4)_A0883  \
 index
 ACAAGCTCAGTTGAAA-2       -0.029878       -1.639316               1.971602
 ACCAACAGTAATGATG-2        0.467237       -1.729988               1.405506
 GGGTAGATCACTGATG-2       -0.024621       -0.940912               1.584817
 TTGTTCACATGCGGTC-2       -0.572634       -1.671246               1.547630
 ATCCACCTCGTGTCAA-2       -0.797552       -1.490699               1.217351
 ...                            ...             ...                    ...
 AGGCATTAGTTGGCGA-2       -0.564378       -0.969843               1.472504
 TGTAAGCAGGGATGTC-2       -0.843529       -1.536676               1.682200
 TCGATTTAGTCATCGT-2        0.304179       -1.487580               1.402791
 TTGGGATCATCTAGAC-2       -0.201822       -2.147732               1.110364
 CAGAGCCGTAGGGAGG-2       -0.162527       -1.771965               1.000624

                     ADT_ENPP1_A0891  ADT_CD150(SLAM)_A0203  \
 index
 ACAAGCTCAGTTGAAA-2         0.758579              -0.029878
 ACCAACAGTAATGATG-2         0.061772               0.467237
 GGGTAGATCACTGATG-2        -0.247764               1.361673
 TTGTTCACATGCGGTC-2         0.120514               0.408196
 ATCCACCTCGTGTCAA-2        -0.104405               1.553823
 ...                             ...                    ...
 AGGCATTAGTTGGCGA-2         0.734905              -0.053552
 TGTAAGCAGGGATGTC-2         0.542766               0.072762
 TCGATTTAGTCATCGT-2         0.815005               1.456859
 TTGGGATCATCTAGAC-2         0.624856               0.491325
 CAGAGCCGTAGGGAGG-2         0.425259               2.518494

                     ADT_CD155(PVR)_A1011
 index
 ACAAGCTCAGTTGAAA-2             -1.639316
 ACCAACAGTAATGATG-2              0.667907
 GGGTAGATCACTGATG-2             -0.940912
 TTGTTCACATGCGGTC-2              0.813661
 ATCCACCTCGTGTCAA-2              0.588742
 ...                                  ...
 AGGCATTAGTTGGCGA-2             -1.662990
 TGTAAGCAGGGATGTC-2              0.409234
 TCGATTTAGTCATCGT-2             -1.487580
 TTGGGATCATCTAGAC-2              0.154853
 CAGAGCCGTAGGGAGG-2             -0.385671

 [1066 rows x 198 columns])

In [13]:
X = X.drop(X_test.index)   
y = y.drop(y_test.index)   
y = y.loc[X.index, :]   
X, y

(index               0610007P14Rik  0610009B22Rik  0610009L18Rik  \
 index
 CAGGGCTAGAGTTGCG-2       0.260179       0.339209       3.141996
 CTGTCGTCAACAGATA-2       0.036023       0.183768       2.749047
 AGGTAGGTCGTTACCC-2       0.266208       0.297080       2.932774
 AACCTTTAGAGCACTG-2       0.237665       0.375749       2.876952
 GTATTGGAGTGCGTCC-2       0.300299       0.626066       2.366092
 ...                           ...            ...            ...
 AGAACAAGTTACCCAA-2       0.255741       0.270103       2.979447
 AGTGATCTCAAGGTGG-2       0.438720       0.528180       2.988067
 TGGAGGACAGTGTGGA-2       0.398481       0.403486       2.485387
 GACGCTGCATCGAAGG-2       0.373597       0.383767       2.959528
 ATGCATGCAACCACAT-2       0.389902       0.604653       2.662775

 index               0610009O20Rik  0610010F05Rik  0610010K14Rik  \
 index
 CAGGGCTAGAGTTGCG-2       0.003803       0.174364       0.026319
 CTGTCGTCAACAGATA-2       0.003661       0.046581       0.032478
 AGGTAGGTCGTTACCC-2       0.003713       0.092314       0.047222
 AACCTTTAGAGCACTG-2       0.003825       0.077410       0.033912
 GTATTGGAGTGCGTCC-2       0.010775       0.066357       0.109348
 ...                           ...            ...            ...
 AGAACAAGTTACCCAA-2       0.003729       0.126193       0.022169
 AGTGATCTCAAGGTGG-2       0.003714       0.148426       0.029334
 TGGAGGACAGTGTGGA-2       0.047439       0.196185       0.029459
 GACGCTGCATCGAAGG-2       0.003706       0.157675       0.029269
 ATGCATGCAACCACAT-2       0.007661       0.253408       0.011470

 index               0610011F06Rik  0610012G03Rik  0610030E20Rik  \
 index
 CAGGGCTAGAGTTGCG-2       0.003803       0.062755       0.564260
 CTGTCGTCAACAGATA-2       0.003661       0.057029       0.087735
 AGGTAGGTCGTTACCC-2       0.014769       0.064807       0.207514
 AACCTTTAGAGCACTG-2       0.022735       0.063120       0.222440
 GTATTGGAGTGCGTCC-2       0.003604       0.059576       0.079783
 ...                           ...            ...            ...
 AGAACAAGTTACCCAA-2       0.003729       0.061579       0.180666
 AGTGATCTCAAGGTGG-2       0.003714       0.061338       0.222593
 TGGAGGACAGTGTGGA-2       0.003730       0.065102       0.061594
 GACGCTGCATCGAAGG-2       0.003706       0.061204       0.257201
 ATGCATGCAACCACAT-2       0.003838       0.066928       0.077659

 index               0610037L13Rik  ...    mt-Co2    mt-Co3   mt-Cytb  \
 index                              ...
 CAGGGCTAGAGTTGCG-2       0.230369  ...  0.233391  0.492396  1.922844
 CTGTCGTCAACAGATA-2       0.234354  ...  0.888095  0.271381  1.997084
 AGGTAGGTCGTTACCC-2       0.466958  ...  0.254742  0.462284  2.140351
 AACCTTTAGAGCACTG-2       0.569014  ...  0.213192  0.321670  2.322221
 GTATTGGAGTGCGTCC-2       0.225354  ...  0.270440  0.156760  1.587724
 ...                           ...  ...       ...       ...       ...
 AGAACAAGTTACCCAA-2       0.360043  ...  0.168113  0.393366  2.065051
 AGTGATCTCAAGGTGG-2       0.263447  ...  0.210608  0.464773  2.210405
 TGGAGGACAGTGTGGA-2       0.112960  ...  0.161816  0.287133  2.374915
 GACGCTGCATCGAAGG-2       0.337168  ...  0.191962  0.352943  2.194021
 ATGCATGCAACCACAT-2       0.041430  ...  0.098783  0.213835  2.693936

 index                 mt-Nd1    mt-Nd2    mt-Nd3    mt-Nd4   mt-Nd4l  \
 index
 CAGGGCTAGAGTTGCG-2  0.097910  0.104796  0.852222  0.649376  0.376498
 CTGTCGTCAACAGATA-2  0.091089  0.097764  0.473254  0.262957  0.186815
 AGGTAGGTCGTTACCC-2  0.099075  0.105789  0.394436  0.455231  0.340347
 AACCTTTAGAGCACTG-2  0.119095  0.108835  0.332722  0.441945  0.679802
 GTATTGGAGTGCGTCC-2  0.138064  0.102853  1.137713  0.262140  0.339629
 ...                      ...       ...       ...       ...       ...
 AGAACAAGTTACCCAA-2  0.119585  0.102871  0.697516  0.624217  0.420721
 AGTGATCTCAAGGTGG-2  0.210608  0.102477  0.949796  0.562685  0.534741
 TGGAGGACAGTGTGGA-2  0.171307  0.106262  0.373072  0.273012  0.383313
 GACGCTGCATCGAAGG-2  0.254326  0.102258  0.796503  0.487014  0.456908
 ATGCATGCAACCACAT-2  0.253408  0.109180  0.452967  0.479503  0.418141

 index                 mt-Nd5    mt-Nd6
 index
 CAGGGCTAGAGTTGCG-2  0.478328  4.241872
 CTGTCGTCAACAGATA-2  0.136904  4.181556
 AGGTAGGTCGTTACCC-2  0.148370  4.615833
 AACCTTTAGAGCACTG-2  0.152552  4.678462
 GTATTGGAGTGCGTCC-2  0.144335  4.347171
 ...                      ...       ...
 AGAACAAGTTACCCAA-2  0.145759  4.479029
 AGTGATCTCAAGGTGG-2  0.145213  4.392052
 TGGAGGACAGTGTGGA-2  0.152234  4.736908
 GACGCTGCATCGAAGG-2  0.144909  4.574900
 ATGCATGCAACCACAT-2  0.156320  4.663983

 [6039 rows x 13553 columns],
                     ADT_CD339(Jagged1)_A0887  ADT_CD272(BTLA)_A0881  \
 index
 CAGGGCTAGAGTTGCG-2                  0.985754              -0.554691
 CTGTCGTCAACAGATA-2                  0.564183              -0.224274
 AGGTAGGTCGTTACCC-2                  0.682649               0.577289
 AACCTTTAGAGCACTG-2                  0.910536              -0.555801
 GTATTGGAGTGCGTCC-2                  0.543250              -0.437580
 ...                                      ...                    ...
 AGAACAAGTTACCCAA-2                  1.329627              -0.567493
 AGTGATCTCAAGGTGG-2                  0.664184              -1.040565
 TGGAGGACAGTGTGGA-2                  1.021853               1.090846
 GACGCTGCATCGAAGG-2                  1.125539              -0.098236
 ATGCATGCAACCACAT-2                  0.419823               0.825288

                     ADT_ESAM_A0596  ADT_CD63_A0559  ADT_CD200(OX2)_A0079  \
 index
 CAGGGCTAGAGTTGCG-2       -0.267009       -0.267009              0.744592
 CTGTCGTCAACAGATA-2       -0.224274        0.651195              0.468873
 AGGTAGGTCGTTACCC-2       -0.926789       -0.233642             -0.010498
 AACCTTTAGAGCACTG-2       -0.044975       -0.268119              0.291497
 GTATTGGAGTGCGTCC-2        1.171858        0.409718              0.409718
 ...                            ...             ...                   ...
 AGAACAAGTTACCCAA-2        0.279805        0.731790             -0.056667
 AGTGATCTCAAGGTGG-2       -0.124274        0.058048              0.463513
 TGGAGGACAGTGTGGA-2       -0.924057        0.328706              1.473839
 GACGCTGCATCGAAGG-2       -0.609062        0.690221              0.084085
 ATGCATGCAACCACAT-2        0.132141       -0.273324              1.048432

                     ADT_CD197(CCR7)_A0377  ADT_CD2_A0892  ADT_PIR-A-B_A0882  \
 index
 CAGGGCTAGAGTTGCG-2              -0.267009       2.741146          -0.043866
 CTGTCGTCAACAGATA-2              -0.041952       2.173621           0.363513
 AGGTAGGTCGTTACCC-2              -0.521324       2.697552          -0.233642
 AACCTTTAGAGCACTG-2              -0.268119       2.257610          -0.555801
 GTATTGGAGTGCGTCC-2              -0.437580       0.255568           1.508331
 ...                                   ...            ...                ...
 AGAACAAGTTACCCAA-2              -0.567493       2.715921          -0.567493
 AGTGATCTCAAGGTGG-2               0.463513       3.200762           0.345730
 TGGAGGACAGTGTGGA-2              -0.230909       2.071676           0.174556
 GACGCTGCATCGAAGG-2               0.084085       2.661774          -0.609062
 ATGCATGCAACCACAT-2               0.132141       1.774369          -0.050180

                     ADT_CD278(ICOS)_A0171  ADT_CD273(B7-DC_PD-L2)_A0914  ...  \
 index                                                                    ...
 CAGGGCTAGAGTTGCG-2               0.138456                      0.138456  ...
 CTGTCGTCAACAGATA-2               0.112198                     -0.447418  ...
 AGGTAGGTCGTTACCC-2               0.777959                     -0.233642  ...
 AACCTTTAGAGCACTG-2               0.137346                     -0.555801  ...
 GTATTGGAGTGCGTCC-2               0.255568                     -0.437580  ...
 ...                                   ...                           ...  ...
 AGAACAAGTTACCCAA-2               0.636480                     -0.972958  ...
 AGTGATCTCAAGGTGG-2               0.568873                     -0.635099  ...
 TGGAGGACAGTGTGGA-2              -0.230909                     -0.518592  ...
 GACGCTGCATCGAAGG-2               0.371768                     -1.707674  ...
 ATGCATGCAACCACAT-2              -0.273324                     -0.561006  ...

                     ADT_CD371(CLEC12A)_A0825  ADT_CD106_A0226  \
 index
 CAGGGCTAGAGTTGCG-2                 -0.960156        -0.043866
 CTGTCGTCAACAGATA-2                 -0.447418        -0.224274
 AGGTAGGTCGTTACCC-2                 -1.619936        -0.926789
 AACCTTTAGAGCACTG-2                 -0.268119        -0.555801
 GTATTGGAGTGCGTCC-2                 -0.149897         0.409718
 ...                                      ...              ...
 AGAACAAGTTACCCAA-2                  0.125654        -0.567493
 AGTGATCTCAAGGTGG-2                 -1.040565        -0.635099
 TGGAGGACAGTGTGGA-2                 -0.518592        -0.518592
 GACGCTGCATCGAAGG-2                 -0.609062         0.084085
 ATGCATGCAACCACAT-2                 -1.659618         0.286292

                     ADT_CD1d(CD1.1_Ly-38)_A0851  ADT_FceRIa_A0115  \
 index
 CAGGGCTAGAGTTGCG-2                    -0.043866         -0.267009
 CTGTCGTCAACAGATA-2                    -0.224274         -0.224274
 AGGTAGGTCGTTACCC-2                     0.777959         -0.521324
 AACCTTTAGAGCACTG-2                     0.542812         -0.555801
 GTATTGGAGTGCGTCC-2                     0.661033         -0.437580
 ...                                         ...               ...
 AGAACAAGTTACCCAA-2                     0.125654         -0.567493
 AGTGATCTCAAGGTGG-2                    -0.347417         -1.040565
 TGGAGGACAGTGTGGA-2                     0.947745         -0.230909
 GACGCTGCATCGAAGG-2                    -0.098236         -1.014527
 ATGCATGCAACCACAT-2                     0.738277          0.132141

                     ADT_PLZF_A0878  ADT_CD83_A0562  ADT_CD26(DPP-4)_A0883  \
 index
 CAGGGCTAGAGTTGCG-2       -0.267009       -0.960156               1.957614
 CTGTCGTCAACAGATA-2       -0.735100       -1.833712               0.938877
 AGGTAGGTCGTTACCC-2       -0.233642       -1.619936               1.471107
 AACCTTTAGAGCACTG-2       -0.268119       -1.654413               1.341319
 GTATTGGAGTGCGTCC-2        0.255568       -1.536192               1.759645
 ...                            ...             ...                    ...
 AGAACAAGTTACCCAA-2        0.413336       -1.666105               1.860255
 AGTGATCTCAAGGTGG-2        0.058048       -1.733712               1.732024
 TGGAGGACAGTGTGGA-2       -0.518592       -0.924057               1.155385
 GACGCTGCATCGAAGG-2       -0.321380       -1.707674               2.005898
 ATGCATGCAACCACAT-2       -1.659618       -0.966471               1.559258

                     ADT_ENPP1_A0891  ADT_CD150(SLAM)_A0203  \
 index
 CAGGGCTAGAGTTGCG-2         0.911646               0.543921
 CTGTCGTCAACAGATA-2        -0.224274              -0.447418
 AGGTAGGTCGTTACCC-2         0.459506               0.459506
 AACCTTTAGAGCACTG-2        -0.268119              -0.268119
 GTATTGGAGTGCGTCC-2         0.661033               0.255568
 ...                             ...                    ...
 AGAACAAGTTACCCAA-2         0.731790               0.636480
 AGTGATCTCAAGGTGG-2        -0.347417               0.664184
 TGGAGGACAGTGTGGA-2         0.780691               1.090846
 GACGCTGCATCGAAGG-2         0.489551              -0.609062
 ATGCATGCAACCACAT-2         0.132141               1.559258

                     ADT_CD155(PVR)_A1011
 index
 CAGGGCTAGAGTTGCG-2             -0.267009
 CTGTCGTCAACAGATA-2             -0.224274
 AGGTAGGTCGTTACCC-2              0.459506
 AACCTTTAGAGCACTG-2              1.523641
 GTATTGGAGTGCGTCC-2             -1.536192
 ...                                  ...
 AGAACAAGTTACCCAA-2             -0.279811
 AGTGATCTCAAGGTGG-2             -0.124274
 TGGAGGACAGTGTGGA-2             -0.518592
 GACGCTGCATCGAAGG-2             -0.321380
 ATGCATGCAACCACAT-2             -0.966471

 [6039 rows x 198 columns])

## Convert gene and protein expression to Torch Tensors

In [14]:
X = torch.tensor(X.values)
X = X.type(torch.FloatTensor)
X = X.to("cuda")
y = torch.tensor(y.values)
y = y.type(torch.FloatTensor)
y = y.to("cuda")
X, y

(tensor([[0.2602, 0.3392, 3.1420,  ..., 0.3765, 0.4783, 4.2419],
         [0.0360, 0.1838, 2.7490,  ..., 0.1868, 0.1369, 4.1816],
         [0.2662, 0.2971, 2.9328,  ..., 0.3403, 0.1484, 4.6158],
         ...,
         [0.3985, 0.4035, 2.4854,  ..., 0.3833, 0.1522, 4.7369],
         [0.3736, 0.3838, 2.9595,  ..., 0.4569, 0.1449, 4.5749],
         [0.3899, 0.6047, 2.6628,  ..., 0.4181, 0.1563, 4.6640]],
        device='cuda:0'),
 tensor([[ 0.9858, -0.5547, -0.2670,  ...,  0.9116,  0.5439, -0.2670],
         [ 0.5642, -0.2243, -0.2243,  ..., -0.2243, -0.4474, -0.2243],
         [ 0.6826,  0.5773, -0.9268,  ...,  0.4595,  0.4595,  0.4595],
         ...,
         [ 1.0219,  1.0908, -0.9241,  ...,  0.7807,  1.0908, -0.5186],
         [ 1.1255, -0.0982, -0.6091,  ...,  0.4896, -0.6091, -0.3214],
         [ 0.4198,  0.8253,  0.1321,  ...,  0.1321,  1.5593, -0.9665]],
        device='cuda:0'))

In [15]:
X_test = torch.tensor(X_test.values).to("cuda")
X_test = X_test.type(torch.FloatTensor)
X_test = X_test.to("cuda")
y_test = torch.tensor(y_test.values).to("cuda")
y_test = y_test.type(torch.FloatTensor)
y_test = y_test.to("cuda")
X_test, y_test

(tensor([[0.4461, 0.4562, 2.2621,  ..., 0.4787, 0.1616, 4.7438],
         [0.1561, 0.3589, 2.7647,  ..., 0.3667, 0.1496, 4.4955],
         [0.5391, 0.4763, 2.3050,  ..., 0.4811, 0.1569, 4.2747],
         ...,
         [0.4423, 0.5368, 2.6236,  ..., 0.3218, 0.1531, 4.5405],
         [0.6390, 0.9622, 2.3012,  ..., 0.5675, 0.1618, 4.6492],
         [0.4174, 0.6731, 2.6111,  ..., 0.4433, 0.1615, 4.5318]],
        device='cuda:0'),
 tensor([[ 0.9256,  0.4401,  0.1524,  ...,  0.7586, -0.0299, -1.6393],
         [ 0.7549, -0.1205, -0.1205,  ...,  0.0618,  0.4672,  0.6679],
         [ 0.6685,  0.3119, -0.5354,  ..., -0.2478,  1.3617, -0.9409],
         ...,
         [ 1.0774,  1.0774, -0.1013,  ...,  0.8150,  1.4569, -1.4876],
         [ 0.6855,  0.1549, -0.3560,  ...,  0.6249,  0.4913,  0.1549],
         [ 0.7129, -0.3857, -0.6734,  ...,  0.4253,  2.5185, -0.3857]],
        device='cuda:0'))

## Define model network

In [16]:
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        # self.fc1 = nn.Linear(14505, 1000)
        self.fc1 = nn.Linear(X.shape[1], 1000)
        self.fc2 = nn.Linear(1000, 256)
        self.fc3 = nn.ModuleDict({})
        for p in protein_list:
            self.fc3[p] = nn.Linear(256, 64)
        self.fc4 = nn.ModuleDict({})
        for p in protein_list:
            self.fc4[p] = nn.Linear(64, 1)
#
    def forward(self, x):
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        outputs = {}
        for p in protein_list:
            outputs[p] = self.fc4[p](F.relu(self.fc3[p](x)))
        return outputs

## Initialize network and set training hyperparameters

In [17]:
net = Net().to("cuda")
net

Net(
  (fc1): Linear(in_features=13553, out_features=1000, bias=True)
  (fc2): Linear(in_features=1000, out_features=256, bias=True)
  (fc3): ModuleDict(
    (ADT_CD339(Jagged1)_A0887): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD272(BTLA)_A0881): Linear(in_features=256, out_features=64, bias=True)
    (ADT_ESAM_A0596): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD63_A0559): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD200(OX2)_A0079): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD197(CCR7)_A0377): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD2_A0892): Linear(in_features=256, out_features=64, bias=True)
    (ADT_PIR-A-B_A0882): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD278(ICOS)_A0171): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD273(B7-DC_PD-L2)_A0914): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD124(IL-4Ra)_A0916): Linear(in_features=256, out_features=64, bias=True)
    (ADT_FolateReceptorb(FR-b)_A0564): Linear(in_features=256, out_features=64, bias=True)
    (ADT_XCR1_A0568): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD314(NKG2D)_A0835): Linear(in_features=256, out_features=64, bias=True)
    (ADT_IL-21Receptor_A0879): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD79b(Igb)_A0561): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD170(Singlec-F)_A0431): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD20_A0192): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD36_A0555): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD134(OX-40)_A0195): Linear(in_features=256, out_features=64, bias=True)
    (ADT_Ly49D_A0841): Linear(in_features=256, out_features=64, bias=True)
    (ADT_IgD_A0571): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD45/2_A0157): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD11b_A0014): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD9_A0813): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD198(CCR8)_A0907): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD107a(LAMP-1)_A0905): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD34_A0857): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD29_A0570): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD62P(P-selectin)_A0229): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD22_A0827): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD159a(NKG2AB6)_A0927): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD85k(gp49Receptor)_A1007): Linear(in_features=256, out_features=64, bias=True)
    (ADT_GABRB3_A0435): Linear(in_features=256, out_features=64, bias=True)
    (ADT_Ly-6G-Ly-6C(Gr-1)_A0116): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD335(NKp46)_A0184): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD185(CXCR5)_A0846): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD160_A1006): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD200R3_A0809): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD8b(Ly-3)_A0230): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD270(HVEM)_A0885): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD14_A0424): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD300LG(Nepmucin)_A0416): Linear(in_features=256, out_features=64, bias=True)
    (ADT_KCC2_A0438): Linear(in_features=256, out_features=64, bias=True)
    (ADT_Mac-2(Galectin-3)_A0895): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD16-32_A0109): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD4_A0001): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD34_A0823): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD194(CCR4)_A0833): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD23_A0108): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD40_A0903): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD279(PD-1)_A0004): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD200R(OX2R)_A0807): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD326(Ep-CAM)_A0449): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD357(GITR)_A0193): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD115(CSF-1R)_A0105): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD38_A0557): Linear(in_features=256, out_features=64, bias=True)
    (ADT_TLR4(CD284)-MD2Complex_A0875): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD41_A0443): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD278(ICOS)_A0847): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD252(OX40Ligand)_A0924): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD43_A0110): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD5_A0111): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD11a_A0595): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD169(Siglec-1)_A0440): Linear(in_features=256, out_features=64, bias=True)
    (ADT_MAdCAM-1_A0232): Linear(in_features=256, out_features=64, bias=True)
    (ADT_IRF4_A0249): Linear(in_features=256, out_features=64, bias=True)
    (ADT_Ly49G_A0840): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD105_A0812): Linear(in_features=256, out_features=64, bias=True)
    (ADT_TCRr-d_A0121): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD102_A0104): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD192(CCR2)_A0426): Linear(in_features=256, out_features=64, bias=True)
    (ADT_NK-1/1_A0118): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD73_A0077): Linear(in_features=256, out_features=64, bias=True)
    (ADT_DLL1_A0884): Linear(in_features=256, out_features=64, bias=True)
    (ADT_H-2KbboundtoSIINFEKL_A0231): Linear(in_features=256, out_features=64, bias=True)
    (ADT_anti-P2RY12_A0415): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD68_A0560): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD44_A0073): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD28_A0204): Linear(in_features=256, out_features=64, bias=True)
    (ADT_DR3(TNFRSF25)_A0836): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD95(Fas)_A0917): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD117(c-Kit)_A0012): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD21-CD35(CR2-CR1)_A0107): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD138(Syndecan-1)_A0810): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD184(CXCR4)_A0444): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD140a_A0573): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD15(SSEA-1)_A0076): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD3e_A0094): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD183(CXCR3)_A0228): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD193(CCR3)_A0808): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD135_A0098): Linear(in_features=256, out_features=64, bias=True)
    (ADT_KLRG1(MAFA)_A0250): Linear(in_features=256, out_features=64, bias=True)
    (ADT_4-1BBLigand(CD137L)_A0890): Linear(in_features=256, out_features=64, bias=True)
    (ADT_Ly-6G_A0015): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD49b_A0421): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD120b(TNFRTypeII-p75)_A0893): Linear(in_features=256, out_features=64, bias=True)
    (ADT_TCRVr3_A0210): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD51_A1008): Linear(in_features=256, out_features=64, bias=True)
    (ADT_TCRVr1/1-Cr4_A0209): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD54_A0074): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD223(LAG-3)_A0378): Linear(in_features=256, out_features=64, bias=True)
    (ADT_Ly-6A-E(Sca-1)_A0130): Linear(in_features=256, out_features=64, bias=True)
    (ADT_Ly-6C_A0013): Linear(in_features=256, out_features=64, bias=True)
    (ADT_MERTK(Mer)_A0565): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD31_A0904): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD8a_A0002): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD196(CCR6)_A0225): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD300c-d_A0876): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD69_A0197): Linear(in_features=256, out_features=64, bias=True)
    (ADT_Notch1_A0442): Linear(in_features=256, out_features=64, bias=True)
    (ADT_TCRVb13/1_A0908): Linear(in_features=256, out_features=64, bias=True)
    (ADT_integrinb7_A0214): Linear(in_features=256, out_features=64, bias=True)
    (ADT_IgM_A0450): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD182(CXCR2)_A0909): Linear(in_features=256, out_features=64, bias=True)
    (ADT_Ly49H_A0839): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD186(CXCR6)_A0926): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD201(EPCR)_A0439): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD94_A1009): Linear(in_features=256, out_features=64, bias=True)
    (ADT_TCRVb5/1_5/2_A0354): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD90/2_A0075): Linear(in_features=256, out_features=64, bias=True)
    (ADT_JAML_A0877): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD309(VEGFR2_Flk-1)_A0553): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD253(TRAIL)_A0925): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD55(DAF)_A0558): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD172a(SIRPa)_A0422): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD86_A0200): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD195(CCR5)_A0376): Linear(in_features=256, out_features=64, bias=True)
    (ADT_Notch4_A0888): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD62L_A0112): Linear(in_features=256, out_features=64, bias=True)
    (ADT_F4-80_A0114): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD127(IL-7Ra)_A0198): Linear(in_features=256, out_features=64, bias=True)
    (ADT_SiglecH_A0119): Linear(in_features=256, out_features=64, bias=True)
    (ADT_TCRVb8/1_8/2_A0235): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD207(Langerin)_A0437): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD45R-B220_A0103): Linear(in_features=256, out_features=64, bias=True)
    (ADT_PanendothelialCellAntigen_A0381): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD61_A0910): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD49d_A0078): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD90/1(Thy-1/1)_A0380): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD301a(MGL1)_A0551): Linear(in_features=256, out_features=64, bias=True)
    (ADT_Ly108_A0930): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD64(FcrRI)_A0202): Linear(in_features=256, out_features=64, bias=True)
    (ADT_D62E(E-selectin)_A0379): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD370(CLEC9A_DNGR1)_A0556): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD11c_A0106): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD49a_A0850): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD178(FasL)_A1012): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD365(Tim-1)_A1013): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD274(B7-H1_PD-L1)_A0190): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD3_A0182): Linear(in_features=256, out_features=64, bias=True)
    (ADT_I-A-I-E_A0117): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD27_A0191): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD163_A0417): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD45/1_A0178): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD206(MMR)_A0173): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD39_A0834): Linear(in_features=256, out_features=64, bias=True)
    (ADT_TER-119-ErythroidCells_A0122): Linear(in_features=256, out_features=64, bias=True)
    (ADT_GITRLigand_A0880): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD19_A0093): Linear(in_features=256, out_features=64, bias=True)
    (ADT_Ly-49A_A0842): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD204(Msr1)_A0448): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD25_A0097): Linear(in_features=256, out_features=64, bias=True)
    (ADT_TCRVr2_A0211): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD122(IL-2Rb)_A0227): Linear(in_features=256, out_features=64, bias=True)
    (ADT_TCRbchain_A0120): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD366(Tim-3)_A0003): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD226(DNAM-1)_A0852): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD317(BST2_PDCA-1)_A0811): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD80_A0849): Linear(in_features=256, out_features=64, bias=True)
    (ADT_Tim-4_A0567): Linear(in_features=256, out_features=64, bias=True)
    (ADT_Slc7a1(Cat-1_ERR)_A0889): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD137_A0194): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD103_A0201): Linear(in_features=256, out_features=64, bias=True)
    (ADT_P2X7R_A0824): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD304(Neuropilin-1)_A0552): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD199(CCR9)_A0854): Linear(in_features=256, out_features=64, bias=True)
    (ADT_IL-33Ra(IL1RL1_ST2)_A0837): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD301b(MGL2)_A0566): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD152_A0388): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD71_A0441): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CX3CR1_A0563): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD45_A0096): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD48_A0429): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD309(VEGFR2_Flk-1)_A0554): Linear(in_features=256, out_features=64, bias=True)
    (ADT_TIGIT(Vstm3)_A0848): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD93(AA4/1_earlyBlineage)_A0113): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD24_A0212): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD371(CLEC12A)_A0825): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD106_A0226): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD1d(CD1/1_Ly-38)_A0851): Linear(in_features=256, out_features=64, bias=True)
    (ADT_FceRIa_A0115): Linear(in_features=256, out_features=64, bias=True)
    (ADT_PLZF_A0878): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD83_A0562): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD26(DPP-4)_A0883): Linear(in_features=256, out_features=64, bias=True)
    (ADT_ENPP1_A0891): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD150(SLAM)_A0203): Linear(in_features=256, out_features=64, bias=True)
    (ADT_CD155(PVR)_A1011): Linear(in_features=256, out_features=64, bias=True)
  )
  (fc4): ModuleDict(
    (ADT_CD339(Jagged1)_A0887): Linear(in_features=64, out_features=1, bias=True)
    (ADT_CD272(BTLA)_A0881): Linear(in_features=64, out_features=1, bias=True)
    (ADT_ESAM_A0596): Linear(in_features=64, out_features=1, bias=True)
    (ADT_CD63_A0559): Linear(in_features=64, out_features=1, bias=True)
    (ADT_CD200(OX2)_A0079): Linear(in_features=64, out_features=1, bias=True)
    (ADT_CD197(CCR7)_A0377): Linear(in_features=64, out_features=1, bias=True)
    (ADT_CD2_A0892): Linear(in_features=64, out_features=1, bias=True)
    (ADT_PIR-A-B_A0882): Linear(in_features=64, out_features=1, bias=True)
    (ADT_CD278(ICOS)_A0171): Linear(in_features=64, out_features=1, bias=True)
    (ADT_CD273(B7-DC_PD-L2)_A0914): Linear(in_features=64, out_features=1, bias=True)
    (ADT_CD124(IL-4Ra)_A0916): Linear(in_features=64, out_features=1, bias=True)
    (ADT_FolateReceptorb(FR-b)_A0564): Linear(in_features=64, out_features=1, bias=True)
    (ADT_XCR1_A0568): Linear(in_features=64, out_features=1, bias=True)
    (ADT_CD314(NKG2D)_A0835): Linear(in_features=64, out_features=1, bias=True)
    (ADT_IL-21Receptor_A0879): Linear(in_features=64, out_features=1, bias=True)
    (ADT_CD79b(Igb)_A0561): Linear(in_features=64, out_features=1, bias=True)
    (ADT_CD170(Singlec-F)_A0431): Linear(in_features=64, out_features=1, bias=True)
    (ADT_CD20_A0192): Linear(in_features=64, out_features=1, bias=True)
    (ADT_CD36_A0555): Linear(in_features=64, out_features=1, bias=True)
    (ADT_CD134(OX-40)_A0195): Linear(in_features=64, out_features=1, bias=True)
    (ADT_Ly49D_A0841): Linear(in_features=64, out_features=1, bias=True)
    (ADT_IgD_A0571): Linear(in_features=64, out_features=1, bias=True)
    (ADT_CD45/2_A0157): Linear(in_features=64, out_features=1, bias=True)
    (ADT_CD11b_A0014): Linear(in_features=64, out_features=1, bias=True)
    (ADT_CD9_A0813): Linear(in_features=64, out_features=1, bias=True)
    (ADT_CD198(CCR8)_A0907): Linear(in_features=64, out_features=1, bias=True)
    (ADT_CD107a(LAMP-1)_A0905): Linear(in_features=64, out_features=1, bias=True)
    (ADT_CD34_A0857): Linear(in_features=64, out_features=1, bias=True)
    (ADT_CD29_A0570): Linear(in_features=64, out_features=1, bias=True)
    (ADT_CD62P(P-selectin)_A0229): Linear(in_features=64, out_features=1, bias=True)
    (ADT_CD22_A0827): Linear(in_features=64, out_features=1, bias=True)
    (ADT_CD159a(NKG2AB6)_A0927): Linear(in_features=64, out_features=1, bias=True)
    (ADT_CD85k(gp49Receptor)_A1007): Linear(in_features=64, out_features=1, bias=True)
    (ADT_GABRB3_A0435): Linear(in_features=64, out_features=1, bias=True)
    (ADT_Ly-6G-Ly-6C(Gr-1)_A0116): Linear(in_features=64, out_features=1, bias=True)
    (ADT_CD335(NKp46)_A0184): Linear(in_features=64, out_features=1, bias=True)
    (ADT_CD185(CXCR5)_A0846): Linear(in_features=64, out_features=1, bias=True)
    (ADT_CD160_A1006): Linear(in_features=64, out_features=1, bias=True)
    (ADT_CD200R3_A0809): Linear(in_features=64, out_features=1, bias=True)
    (ADT_CD8b(Ly-3)_A0230): Linear(in_features=64, out_features=1, bias=True)
    (ADT_CD270(HVEM)_A0885): Linear(in_features=64, out_features=1, bias=True)
    (ADT_CD14_A0424): Linear(in_features=64, out_features=1, bias=True)
    (ADT_CD300LG(Nepmucin)_A0416): Linear(in_features=64, out_features=1, bias=True)
    (ADT_KCC2_A0438): Linear(in_features=64, out_features=1, bias=True)
    (ADT_Mac-2(Galectin-3)_A0895): Linear(in_features=64, out_features=1, bias=True)
    (ADT_CD16-32_A0109): Linear(in_features=64, out_features=1, bias=True)
    (ADT_CD4_A0001): Linear(in_features=64, out_features=1, bias=True)
    (ADT_CD34_A0823): Linear(in_features=64, out_features=1, bias=True)
    (ADT_CD194(CCR4)_A0833): Linear(in_features=64, out_features=1, bias=True)
    (ADT_CD23_A0108): Linear(in_features=64, out_features=1, bias=True)
    (ADT_CD40_A0903): Linear(in_features=64, out_features=1, bias=True)
    (ADT_CD279(PD-1)_A0004): Linear(in_features=64, out_features=1, bias=True)
    (ADT_CD200R(OX2R)_A0807): Linear(in_features=64, out_features=1, bias=True)

In [18]:
criterion = nn.MSELoss()
optimizer = optim.Adam(net.parameters(), lr=0.001, amsgrad=True, weight_decay=0.001)
max_epochs = 200
n_batches = 32 
patience = 30
best_score = None

Dy = len(protein_list)
estop_counter = pd.Series(np.zeros(Dy), index=protein_list)
early_stop = pd.Series([False] * Dy, index=protein_list)

train_loss = pd.DataFrame(np.zeros(shape=(len(protein_list), max_epochs)), index=protein_list)
test_loss = pd.DataFrame(np.zeros(shape=(len(protein_list), max_epochs)), index=protein_list)

## Start training

In [19]:
for epoch in range(max_epochs):
    if all(early_stop):
        break
    running_loss = pd.Series(np.zeros(Dy), index=protein_list)
    for i in range(int(y.shape[0] / n_batches)):
        local_X, local_y = X[i * n_batches:min((i + 1) * n_batches, X.shape[0] - 1), ], y[i * n_batches:min((i + 1) * n_batches, y.shape[0] - 1), ]
        optimizer.zero_grad()
        outputs_dict = net(local_X)
        loss = None
        for p in protein_list:
            loss_p = criterion(outputs_dict[p], local_y[:, protein_list.index(p):(protein_list.index(p) + 1)])
            if not torch.isnan(loss_p):
                running_loss[p] += loss_p.item()
                if loss is None:
                    loss = loss_p
                else:
                    loss = loss + loss_p
        loss.backward()
        optimizer.step()
        
    avg_loss = (running_loss / int(y.shape[0] / n_batches)).sum()
    train_loss.iloc[:, epoch] = (running_loss / int(y.shape[0] / n_batches))
    print(f"Epoch [{epoch+1}/{max_epochs}], Loss: {avg_loss:.4f}")
    
    test_outputs = net(X_test)   
    test_outputs = [test_outputs[p] for p in protein_list]
    test_outputs = torch.transpose(torch.stack(test_outputs), 0, 1).view(X_test.shape[0], -1)
    test_loss_i = pd.Series([criterion(test_outputs[:, pi], y_test[:, pi]).item() for pi in range(Dy)], index=protein_list)
    test_loss.iloc[:, epoch] = test_loss_i
    if best_score is None:
        best_score = test_loss_i
    else:
        for p in protein_list:
            if test_loss_i[p] > (best_score[p] - 0.001) and (not early_stop[p]):
                estop_counter[p] += 1
                if estop_counter[p] >= patience:
                    early_stop[p] = True
            else:
                best_score[p] = test_loss_i[p]
                estop_counter[p] = 0

Epoch [1/200], Loss: 62.4040
Epoch [2/200], Loss: 53.3566
Epoch [3/200], Loss: 52.2753
Epoch [4/200], Loss: 51.4350
Epoch [5/200], Loss: 50.9515
Epoch [6/200], Loss: 50.6380
Epoch [7/200], Loss: 50.4083
Epoch [8/200], Loss: 50.0918
Epoch [9/200], Loss: 49.8231
Epoch [10/200], Loss: 49.6329
Epoch [11/200], Loss: 49.4754
Epoch [12/200], Loss: 49.2395
Epoch [13/200], Loss: 49.2864
Epoch [14/200], Loss: 48.9536
Epoch [15/200], Loss: 48.8082
Epoch [16/200], Loss: 48.6559
Epoch [17/200], Loss: 48.4677
Epoch [18/200], Loss: 48.3256
Epoch [19/200], Loss: 48.1040
Epoch [20/200], Loss: 48.0008
Epoch [21/200], Loss: 47.8998
Epoch [22/200], Loss: 47.9279
Epoch [23/200], Loss: 48.0963
Epoch [24/200], Loss: 48.0137
Epoch [25/200], Loss: 47.7162
Epoch [26/200], Loss: 47.8139
Epoch [27/200], Loss: 47.6527
Epoch [28/200], Loss: 47.5385
Epoch [29/200], Loss: 47.6414
Epoch [30/200], Loss: 47.8437
Epoch [31/200], Loss: 47.6562
Epoch [32/200], Loss: 47.4075
Epoch [33/200], Loss: 47.3110
Epoch [34/200], Loss: 47.1601
Epoch [35/200], Loss: 47.0628
Epoch [36/200], Loss: 46.9620
Epoch [37/200], Loss: 46.8907
Epoch [38/200], Loss: 47.0186
Epoch [39/200], Loss: 47.1536
Epoch [40/200], Loss: 46.7887
Epoch [41/200], Loss: 46.8255
Epoch [42/200], Loss: 46.7291
Epoch [43/200], Loss: 46.6805
Epoch [44/200], Loss: 46.7543
Epoch [45/200], Loss: 46.8606
Epoch [46/200], Loss: 46.7552
Epoch [47/200], Loss: 46.7661
Epoch [48/200], Loss: 46.4806
Epoch [49/200], Loss: 46.5244
Epoch [50/200], Loss: 46.5138
Epoch [51/200], Loss: 46.3658
Epoch [52/200], Loss: 46.2463
Epoch [53/200], Loss: 46.2811
Epoch [54/200], Loss: 46.2624
Epoch [55/200], Loss: 46.4509
Epoch [56/200], Loss: 46.7215
Epoch [57/200], Loss: 46.4049
Epoch [58/200], Loss: 46.2070
Epoch [59/200], Loss: 46.1982
Epoch [60/200], Loss: 46.0725
Epoch [61/200], Loss: 46.0526
Epoch [62/200], Loss: 46.2104
Epoch [63/200], Loss: 46.0888
Epoch [64/200], Loss: 45.9656
Epoch [65/200], Loss: 45.8916
Epoch [66/200], Loss: 45.8980
Epoch [67/200], Loss: 45.9174
Epoch [68/200], Loss: 46.1183
Epoch [69/200], Loss: 46.1415
Epoch [70/200], Loss: 45.9270
Epoch [71/200], Loss: 45.7002
Epoch [72/200], Loss: 45.6845
Epoch [73/200], Loss: 45.7940
Epoch [74/200], Loss: 45.8301
Epoch [75/200], Loss: 45.8246
Epoch [76/200], Loss: 45.6465
Epoch [77/200], Loss: 45.4314
Epoch [78/200], Loss: 45.4029
Epoch [79/200], Loss: 45.4532
Epoch [80/200], Loss: 45.4772
Epoch [81/200], Loss: 45.6087
Epoch [82/200], Loss: 45.4631
Epoch [83/200], Loss: 45.3792
Epoch [84/200], Loss: 45.2779

## Save the loss during training

In [20]:
train_loss = train_loss.iloc[:, :epoch]
test_loss = test_loss.iloc[:, :epoch]

torch.save(net.state_dict(), f"{base_dir}/model.pth")
train_loss.to_csv(f"{base_dir}/training_loss.csv")
test_loss.to_csv(f"{base_dir}/test_loss.csv")
train_loss, test_loss

(                                0         1         2         3         4   \
 ADT_CD339(Jagged1)_A0887  0.135074  0.126472  0.126466  0.124513  0.123386
 ADT_CD272(BTLA)_A0881     0.237322  0.204731  0.203067  0.201280  0.199983
 ADT_ESAM_A0596            0.276343  0.268064  0.267212  0.263390  0.262368
 ADT_CD63_A0559            0.192539  0.177280  0.175262  0.173157  0.172003
 ADT_CD200(OX2)_A0079      0.234429  0.207769  0.202624  0.200187  0.197933
 ...                            ...       ...       ...       ...       ...
 ADT_CD83_A0562            0.176228  0.155453  0.152500  0.149385  0.147426
 ADT_CD26(DPP-4)_A0883     0.124923  0.094728  0.091342  0.088681  0.087231
 ADT_ENPP1_A0891           0.168174  0.164748  0.161932  0.161262  0.160547
 ADT_CD150(SLAM)_A0203     0.346643  0.295721  0.287815  0.279006  0.273130
 ADT_CD155(PVR)_A1011      0.334776  0.300492  0.290405  0.284636  0.282101

                                 5         6         7         8         9   \
 ADT_CD339(Jagged1)_A0887  0.123744  0.122763  0.121449  0.121157  0.120740
 ADT_CD272(BTLA)_A0881     0.198925  0.198651  0.198206  0.197779  0.197601
 ADT_ESAM_A0596            0.261265  0.260739  0.259573  0.259229  0.258138
 ADT_CD63_A0559            0.171481  0.170546  0.170147  0.170202  0.169406
 ADT_CD200(OX2)_A0079      0.196181  0.196236  0.194515  0.192685  0.191400
 ...                            ...       ...       ...       ...       ...
 ADT_CD83_A0562            0.147761  0.148449  0.145695  0.145509  0.145087
 ADT_CD26(DPP-4)_A0883     0.086440  0.085742  0.083548  0.082700  0.081541
 ADT_ENPP1_A0891           0.160230  0.160101  0.159661  0.159409  0.159052
 ADT_CD150(SLAM)_A0203     0.270087  0.268954  0.265324  0.262948  0.262169
 ADT_CD155(PVR)_A1011      0.281172  0.280219  0.277177  0.277848  0.276659

                           ...        74        75        76        77  \
 ADT_CD339(Jagged1)_A0887  ...  0.112760  0.113006  0.113530  0.112989
 ADT_CD272(BTLA)_A0881     ...  0.184540  0.184628  0.184242  0.184083
 ADT_ESAM_A0596            ...  0.244776  0.244520  0.243387  0.244212
 ADT_CD63_A0559            ...  0.161067  0.160330  0.159277  0.159059
 ADT_CD200(OX2)_A0079      ...  0.171704  0.170773  0.169312  0.169144
 ...                       ...       ...       ...       ...       ...
 ADT_CD83_A0562            ...  0.136853  0.136802  0.136507  0.136206
 ADT_CD26(DPP-4)_A0883     ...  0.075653  0.075410  0.074890  0.075312
 ADT_ENPP1_A0891           ...  0.151218  0.150804  0.150720  0.150401
 ADT_CD150(SLAM)_A0203     ...  0.209616  0.211399  0.209876  0.209017
 ADT_CD155(PVR)_A1011      ...  0.256678  0.255153  0.255188  0.255152

                                 78        79        80        81        82  \
 ADT_CD339(Jagged1)_A0887  0.112363  0.112155  0.112607  0.112789  0.113235
 ADT_CD272(BTLA)_A0881     0.183712  0.184309  0.184900  0.184332  0.182980
 ADT_ESAM_A0596            0.244062  0.243439  0.243397  0.242834  0.243709
 ADT_CD63_A0559            0.159653  0.159523  0.161013  0.159449  0.158353
 ADT_CD200(OX2)_A0079      0.168059  0.167911  0.167371  0.167298  0.167544
 ...                            ...       ...       ...       ...       ...
 ADT_CD83_A0562            0.136839  0.137149  0.137737  0.137668  0.137951
 ADT_CD26(DPP-4)_A0883     0.075818  0.075375  0.075425  0.075009  0.074813
 ADT_ENPP1_A0891           0.150886  0.151395  0.151304  0.150940  0.151362
 ADT_CD150(SLAM)_A0203     0.208950  0.209045  0.211322  0.208153  0.205540
 ADT_CD155(PVR)_A1011      0.256166  0.258317  0.259750  0.257383  0.255827

                                 83
 ADT_CD339(Jagged1)_A0887  0.112854
 ADT_CD272(BTLA)_A0881     0.183043
 ADT_ESAM_A0596            0.242885
 ADT_CD63_A0559            0.158485
 ADT_CD200(OX2)_A0079      0.167414
 ...                            ...
 ADT_CD83_A0562            0.137116
 ADT_CD26(DPP-4)_A0883     0.075198
 ADT_ENPP1_A0891           0.151078
 ADT_CD150(SLAM)_A0203     0.204902
 ADT_CD155(PVR)_A1011      0.254948

 [198 rows x 84 columns],
                                 0         1         2         3         4   \
 ADT_CD339(Jagged1)_A0887  0.117581  0.116972  0.112789  0.115724  0.110892
 ADT_CD272(BTLA)_A0881     0.203802  0.198297  0.197768  0.196853  0.197874
 ADT_ESAM_A0596            0.257050  0.258258  0.252976  0.250969  0.250115
 ADT_CD63_A0559            0.180200  0.178306  0.175739  0.175427  0.176467
 ADT_CD200(OX2)_A0079      0.208966  0.204691  0.201033  0.204294  0.198770
 ...                            ...       ...       ...       ...       ...
 ADT_CD83_A0562            0.157037  0.164367  0.154812  0.157061  0.150912
 ADT_CD26(DPP-4)_A0883     0.108462  0.105153  0.096019  0.096301  0.092681
 ADT_ENPP1_A0891           0.177688  0.174211  0.173004  0.172716  0.171524
 ADT_CD150(SLAM)_A0203     0.297251  0.285409  0.280811  0.283213  0.284661
 ADT_CD155(PVR)_A1011      0.290693  0.283134  0.281147  0.278916  0.283263

                                 5         6         7         8         9   \
 ADT_CD339(Jagged1)_A0887  0.111102  0.110586  0.110955  0.109434  0.111449
 ADT_CD272(BTLA)_A0881     0.198409  0.196354  0.196416  0.196223  0.197210
 ADT_ESAM_A0596            0.249897  0.248626  0.252313  0.249553  0.249663
 ADT_CD63_A0559            0.175110  0.174632  0.175340  0.174283  0.173601
 ADT_CD200(OX2)_A0079      0.197176  0.198449  0.196500  0.195471  0.195123
 ...                            ...       ...       ...       ...       ...
 ADT_CD83_A0562            0.151542  0.150997  0.161377  0.151394  0.153231
 ADT_CD26(DPP-4)_A0883     0.093211  0.094529  0.093666  0.093738  0.092652
 ADT_ENPP1_A0891           0.171463  0.171766  0.170523  0.169970  0.169684
 ADT_CD150(SLAM)_A0203     0.281605  0.276971  0.276863  0.281606  0.276030
 ADT_CD155(PVR)_A1011      0.284334  0.281221  0.278028  0.277050  0.278256

                           ...        74        75        76        77  \
 ADT_CD339(Jagged1)_A0887  ...  0.111117  0.111334  0.111683  0.111365
 ADT_CD272(BTLA)_A0881     ...  0.203626  0.198648  0.197685  0.197826
 ADT_ESAM_A0596            ...  0.270317  0.262492  0.261532  0.261877
 ADT_CD63_A0559            ...  0.178449  0.180903  0.185682  0.187958
 ADT_CD200(OX2)_A0079      ...  0.203883  0.200793  0.208745  0.207942
 ...                       ...       ...       ...       ...       ...
 ADT_CD83_A0562            ...  0.155740  0.156424  0.159622  0.162006
 ADT_CD26(DPP-4)_A0883     ...  0.091205  0.089158  0.091057  0.093302
 ADT_ENPP1_A0891           ...  0.178699  0.178767  0.178483  0.179815
 ADT_CD150(SLAM)_A0203     ...  0.287105  0.297282  0.290965  0.288636
 ADT_CD155(PVR)_A1011      ...  0.288448  0.287118  0.290937  0.287748

                                 78        79        80        81        82  \
 ADT_CD339(Jagged1)_A0887  0.110997  0.111056  0.111680  0.111885  0.111840
 ADT_CD272(BTLA)_A0881     0.199232  0.200322  0.201544  0.198355  0.200506
 ADT_ESAM_A0596            0.267135  0.265367  0.273563  0.266373  0.263085
 ADT_CD63_A0559            0.192903  0.183229  0.179996  0.179101  0.176595
 ADT_CD200(OX2)_A0079      0.215285  0.216773  0.214723  0.202599  0.205211
 ...                            ...       ...       ...       ...       ...
 ADT_CD83_A0562            0.160050  0.156035  0.156245  0.154819  0.153475
 ADT_CD26(DPP-4)_A0883     0.095213  0.094738  0.093135  0.099621  0.097215
 ADT_ENPP1_A0891           0.180530  0.178811  0.178495  0.177891  0.178892
 ADT_CD150(SLAM)_A0203     0.294968  0.299173  0.304956  0.288773  0.284686
 ADT_CD155(PVR)_A1011      0.297346  0.292778  0.291391  0.297339  0.290267

                                 83
 ADT_CD339(Jagged1)_A0887  0.112502
 ADT_CD272(BTLA)_A0881     0.200008
 ADT_ESAM_A0596            0.263076
 ADT_CD63_A0559            0.182516
 ADT_CD200(OX2)_A0079      0.201782
 ...                            ...
 ADT_CD83_A0562            0.152909
 ADT_CD26(DPP-4)_A0883     0.092796
 ADT_ENPP1_A0891           0.179983
 ADT_CD150(SLAM)_A0203     0.295698
 ADT_CD155(PVR)_A1011      0.283906

 [198 rows x 84 columns])

## Normalize query raw gene expression

In [21]:
X_pred_raw = x_batch2
X_pred = X_pred_raw.loc[:, gene_list]
X_pred = X_pred.apply(lambda x: np.log((x * 10000.0 / sum(x)) + 1.0), axis=1)
X_pred

index,0610007P14Rik,0610009B22Rik,0610009L18Rik,0610009O20Rik,0610010F05Rik,0610010K14Rik,0610011F06Rik,0610012G03Rik,0610030E20Rik,0610037L13Rik,...,mt-Co2,mt-Co3,mt-Cytb,mt-Nd1,mt-Nd2,mt-Nd3,mt-Nd4,mt-Nd4l,mt-Nd5,mt-Nd6
index,,,,,,,,,,,,,,,,,,,,,
AAACCCAAGCGATCGA-1,0.242766,0.699239,3.661876,0.001771,0.188476,0.063529,0.010580,0.094648,0.290291,0.278284,...,0.244156,0.339453,0.900453,0.120123,0.055176,0.573618,0.369302,0.290291,0.245544,4.916514
AAACCCACACCTCTAC-1,0.471157,0.672287,3.141607,0.003851,0.203506,0.020997,0.011508,0.104318,0.045256,0.043411,...,0.273400,0.267513,1.337267,0.450473,0.081466,0.192428,0.401339,0.466329,0.212905,4.754729
AAACCCACACGTCGTG-1,0.435586,1.030374,3.222365,0.139373,0.197802,0.089357,0.011154,0.099562,0.122977,0.116343,...,0.187007,0.386005,1.062541,0.177660,0.087646,0.247182,0.331156,0.502244,0.301178,4.987180
AAACCCACATGTCTAG-1,0.447606,0.849128,3.394511,0.043327,0.195453,0.048613,0.011009,0.098323,0.060840,0.050369,...,0.206019,0.285367,1.161750,0.269993,0.059103,0.206019,0.207520,0.396810,0.255809,5.674700
AAACCCAGTCAAAGTA-1,0.458393,0.848226,3.563082,0.005488,0.194443,0.021775,0.010947,0.099452,0.097790,0.034261,...,0.195952,0.212404,1.139806,0.294941,0.051833,0.188383,0.203464,0.319230,0.275633,5.241976
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TTTGTTGCATTCCTCG-1,0.546502,1.011894,3.235216,0.010986,0.196586,0.036159,0.010986,0.101454,0.076186,0.034381,...,0.179809,0.208613,1.084175,0.312152,0.055502,0.159612,0.405969,0.399816,0.302675,4.807837
TTTGTTGGTGCTCTTC-1,0.494792,0.727922,3.154365,0.007660,0.204444,0.046941,0.011468,0.103978,0.105709,0.052428,...,0.241360,0.328097,1.045737,0.435645,0.091776,0.272581,0.305693,0.434400,0.337743,5.304375
TTTGTTGTCAGCCTTC-1,0.252563,0.658267,3.361503,0.001876,0.198618,0.063657,0.091460,0.101691,0.239347,0.384907,...,0.433544,0.355073,1.282748,0.219943,0.179969,0.321603,0.574125,0.410144,0.333782,4.612128
TTTGTTGTCCCTTGGT-1,0.313386,0.531877,3.487876,0.001886,0.199531,0.105583,0.011261,0.100475,0.210295,0.429201,...,0.399267,0.544001,0.990665,0.172897,0.117401,0.705508,0.476011,0.464216,0.292474,5.172823
TTTGTTGTCTTACTGT-1,0.429705,0.503242,2.920346,0.013127,0.178063,0.076296,0.009861,0.092990,0.027692,0.068615,...,0.286676,0.312383,1.273042,0.771403,0.086951,0.197231,0.461439,0.649741,0.201291,4.769635

## Convert gene expression to Torch Tensor

In [22]:
X_pred = torch.tensor(X_pred.values)
X_pred = X_pred.type(torch.FloatTensor)
X_pred = X_pred.to("cuda")
X_pred

tensor([[0.2428, 0.6992, 3.6619,  ..., 0.2903, 0.2455, 4.9165],
        [0.4712, 0.6723, 3.1416,  ..., 0.4663, 0.2129, 4.7547],
        [0.4356, 1.0304, 3.2224,  ..., 0.5022, 0.3012, 4.9872],
        ...,
        [0.2526, 0.6583, 3.3615,  ..., 0.4101, 0.3338, 4.6121],
        [0.3134, 0.5319, 3.4879,  ..., 0.4642, 0.2925, 5.1728],
        [0.4297, 0.5032, 2.9203,  ..., 0.6497, 0.2013, 4.7696]],
       device='cuda:0')

## Perform prediction on the query

In [23]:
test_outputs_ = net(X_pred)

def fun(x):
    test_outputs_[x] = test_outputs_[x].detach().cpu().numpy().flatten()

ing = [fun(i) for i in test_outputs_]
test_outputs_ = pd.DataFrame.from_dict(test_outputs_, orient='index')
test_outputs_.columns = X_pred_raw.index
test_outputs_ = test_outputs_.T
test_outputs_.to_csv(f"{base_dir}/test_predicted_protein_expression (cTPnet).csv")
test_outputs_

,ADT_CD339(Jagged1)_A0887,ADT_CD272(BTLA)_A0881,ADT_ESAM_A0596,ADT_CD63_A0559,ADT_CD200(OX2)_A0079,ADT_CD197(CCR7)_A0377,ADT_CD2_A0892,ADT_PIR-A-B_A0882,ADT_CD278(ICOS)_A0171,ADT_CD273(B7-DC_PD-L2)_A0914,...,ADT_CD371(CLEC12A)_A0825,ADT_CD106_A0226,ADT_CD1d(CD1/1_Ly-38)_A0851,ADT_FceRIa_A0115,ADT_PLZF_A0878,ADT_CD83_A0562,ADT_CD26(DPP-4)_A0883,ADT_ENPP1_A0891,ADT_CD150(SLAM)_A0203,ADT_CD155(PVR)_A1011
index,,,,,,,,,,,,,,,,,,,,,
AAACCCAAGCGATCGA-1,0.701519,-0.342424,-0.436930,0.174096,0.097218,-0.087761,2.530185,-0.323219,0.586917,-0.779938,...,-0.748734,-0.361084,0.048087,-0.608738,-0.478255,-1.406853,1.839212,0.294416,0.165791,-0.248224
AAACCCACACCTCTAC-1,0.758352,0.153912,-0.500211,0.044813,0.844480,-0.260867,1.999589,0.510575,-0.007724,-0.978873,...,-0.053089,-0.301036,2.404577,-0.841118,-0.578377,-1.697636,1.358449,0.108661,0.955528,-0.232259
AAACCCACACGTCGTG-1,0.771610,0.374123,-0.395313,0.205485,0.791792,-0.078035,2.479775,0.659072,0.107209,-0.729224,...,-0.065132,-0.250608,1.726287,-0.571043,-0.673993,-1.602600,1.503769,0.283097,0.816887,-0.405219
AAACCCACATGTCTAG-1,0.729030,0.451394,-0.478414,0.151023,1.024541,-0.186371,2.436165,0.679903,0.099520,-0.760503,...,-0.284461,-0.397807,1.612529,-0.776030,-0.659756,-1.587443,1.415689,0.228878,1.168741,-0.418235
AAACCCAGTCAAAGTA-1,0.706716,0.426363,-0.498750,0.102534,1.353212,-0.278737,2.365363,0.326206,0.074335,-0.665942,...,-0.416423,-0.258481,1.091699,-0.821857,-0.675624,-1.586425,1.317187,0.053390,1.368811,-0.403096
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TTTGTTGCATTCCTCG-1,0.742271,0.572464,-0.468024,0.172310,1.387028,-0.150892,2.357247,0.194971,0.130066,-0.759001,...,-0.476170,-0.318289,0.853597,-0.714117,-0.563140,-1.502131,1.313081,0.247673,1.388466,-0.441969
TTTGTTGGTGCTCTTC-1,0.729698,0.576195,-0.471309,0.194047,1.369689,-0.232933,2.422460,0.161858,0.144458,-0.779889,...,-0.449192,-0.248720,0.747555,-0.794246,-0.554636,-1.576740,1.292380,0.270026,1.368184,-0.419234
TTTGTTGTCAGCCTTC-1,0.764950,-0.165404,-0.451516,0.209819,0.211336,-0.086858,2.494130,-0.293906,0.547543,-0.705775,...,-0.860249,-0.357543,0.220537,-0.543087,-0.400196,-1.428550,1.405389,0.235628,0.543697,0.648083
TTTGTTGTCCCTTGGT-1,0.751743,-0.467094,-0.443946,0.146823,0.053441,-0.088709,2.615742,-0.327590,0.611313,-0.786367,...,-0.813317,-0.329304,0.017773,-0.626617,-0.364535,-1.505941,1.704955,0.294057,0.169411,-0.194578
TTTGTTGTCTTACTGT-1,0.699723,0.488924,-0.305284,-0.031218,1.133925,-0.184015,2.451047,0.447188,0.133559,-0.645384,...,-0.425550,-0.280717,1.358111,-0.648295,-0.625330,-1.642830,1.307313,0.194964,1.210014,-0.408817